package constant

/*------------------------------------------------------------------------------
//   This code was generated by template globalconstants.go.tmpl.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "globalconstants.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/

//revive:disable

// #include <godot/gdextension_interface.h>
// #include <stdio.h>
// #include <stdlib.h>
import "C"

const (
	UINT8_MAX  = 255
	UINT16_MAX = 65535
	UINT32_MAX = 4294967295
	INT8_MIN   = -128
	INT8_MAX   = 127
	INT16_MIN  = -32768
	INT16_MAX  = 32767
	INT32_MIN  = -2147483648
	INT32_MAX  = 2147483647
	INT64_MIN  = -9223372036854775808
	INT64_MAX  = 9223372036854775807
)
