package gdclassimpl

import (
	"unsafe"

	. "github.com/godot-go/godot-go/pkg/builtin"
	. "github.com/godot-go/godot-go/pkg/constant"
	. "github.com/godot-go/godot-go/pkg/ffi"
	. "github.com/godot-go/godot-go/pkg/nativestructure"
)

/*------------------------------------------------------------------------------
//   This code was generated by template virtuals.go.tmpl.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "virtuals.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/

// This file catalogs the Category-A virtual surface of Godot's engine classes:
// declared GDVIRTUAL methods whose result feeds a plain wrapper on the same
// class hierarchy. Declarations only — implementing a method here has no
// effect unless it is explicitly bound via ClassDBBindMethodVirtual.
//
// Overriding an engine virtual replaces its behavior wholesale: Godot resolves
// virtual presence once per instance and never falls back to the engine body
// afterwards, so engine-default implementations cannot be reached from
// GDExtension. Verify one override's signature at compile time with an
// anonymous-interface assertion, e.g.:
//
//	var _ interface{ V_Control_GetMaximumSize() Vector2 } = (*MyThing)(nil)

// AudioStreamVirtuals declares the Category-A virtual surface of Godot class AudioStream.
type AudioStreamVirtuals interface {
	V_AudioStream_InstantiatePlayback() RefAudioStreamPlayback
	V_AudioStream_GetLength() float64
	V_AudioStream_IsMonophonic() bool
}

// AudioStreamPlaybackVirtuals declares the Category-A virtual surface of Godot class AudioStreamPlayback.
type AudioStreamPlaybackVirtuals interface {
	V_AudioStreamPlayback_IsPlaying() bool
	V_AudioStreamPlayback_GetLoopCount() int32
	V_AudioStreamPlayback_GetPlaybackPosition() float64
}

// CameraFeedVirtuals declares the Category-A virtual surface of Godot class CameraFeed.
type CameraFeedVirtuals interface {
	V_CameraFeed_SetFormat(index int32, parameters Dictionary) bool
	V_CameraFeed_GetFormats() Array
}

// ControlVirtuals declares the Category-A virtual surface of Godot class Control.
type ControlVirtuals interface {
	V_Control_GetMaximumSize() Vector2
	V_Control_GetMinimumSize() Vector2
	V_Control_GetTooltip(at_position Vector2) String
	V_Control_GetCursorShape(at_position Vector2) int32
}

// EditorExportPlatformExtensionVirtuals declares the Category-A virtual surface of Godot class EditorExportPlatformExtension.
type EditorExportPlatformExtensionVirtuals interface {
	V_EditorExportPlatformExtension_GetOsName() String
	V_EditorExportPlatformExtension_ExportProject(preset RefEditorExportPreset, debug bool, path String, flags EditorExportPlatformDebugFlags) Error
	V_EditorExportPlatformExtension_ExportPack(preset RefEditorExportPreset, debug bool, path String, flags EditorExportPlatformDebugFlags) Error
	V_EditorExportPlatformExtension_ExportZip(preset RefEditorExportPreset, debug bool, path String, flags EditorExportPlatformDebugFlags) Error
	V_EditorExportPlatformExtension_ExportPackPatch(preset RefEditorExportPreset, debug bool, path String, patches PackedStringArray, flags EditorExportPlatformDebugFlags) Error
	V_EditorExportPlatformExtension_ExportZipPatch(preset RefEditorExportPreset, debug bool, path String, patches PackedStringArray, flags EditorExportPlatformDebugFlags) Error
}

// EditorSyntaxHighlighterVirtuals declares the Category-A virtual surface of Godot class EditorSyntaxHighlighter.
type EditorSyntaxHighlighterVirtuals interface {
	V_EditorSyntaxHighlighter_GetName() String
}

// GraphEditVirtuals declares the Category-A virtual surface of Godot class GraphEdit.
type GraphEditVirtuals interface {
	V_GraphEdit_GetConnectionLine(from_position Vector2, to_position Vector2) PackedVector2Array
}

// MeshVirtuals declares the Category-A virtual surface of Godot class Mesh.
type MeshVirtuals interface {
	V_Mesh_GetSurfaceCount() int32
	V_Mesh_SurfaceGetArrays(index int32) Array
	V_Mesh_SurfaceGetBlendShapeArrays(index int32) Array
	V_Mesh_SurfaceGetMaterial(index int32) RefMaterial
	V_Mesh_GetAabb() AABB
}

// MultiplayerAPIExtensionVirtuals declares the Category-A virtual surface of Godot class MultiplayerAPIExtension.
type MultiplayerAPIExtensionVirtuals interface {
	V_MultiplayerAPIExtension_Poll() Error
	V_MultiplayerAPIExtension_GetMultiplayerPeer() RefMultiplayerPeer
	V_MultiplayerAPIExtension_GetUniqueId() int32
	V_MultiplayerAPIExtension_Rpc(peer int32, object Object, method StringName, args Array) Error
	V_MultiplayerAPIExtension_GetRemoteSenderId() int32
	V_MultiplayerAPIExtension_ObjectConfigurationAdd(object Object, configuration Variant) Error
	V_MultiplayerAPIExtension_ObjectConfigurationRemove(object Object, configuration Variant) Error
}

// MultiplayerPeerExtensionVirtuals declares the Category-A virtual surface of Godot class MultiplayerPeerExtension.
type MultiplayerPeerExtensionVirtuals interface {
	V_MultiplayerPeerExtension_GetPacket(r_buffer **uint8, r_buffer_size *Int32T) Error
	V_MultiplayerPeerExtension_PutPacket(buffer *uint8, buffer_size int32) Error
	V_MultiplayerPeerExtension_GetAvailablePacketCount() int32
	V_MultiplayerPeerExtension_GetPacketChannel() int32
	V_MultiplayerPeerExtension_GetPacketMode() MultiplayerPeerTransferMode
	V_MultiplayerPeerExtension_GetTransferChannel() int32
	V_MultiplayerPeerExtension_GetTransferMode() MultiplayerPeerTransferMode
	V_MultiplayerPeerExtension_GetPacketPeer() int32
	V_MultiplayerPeerExtension_GetUniqueId() int32
	V_MultiplayerPeerExtension_IsRefusingNewConnections() bool
	V_MultiplayerPeerExtension_IsServerRelaySupported() bool
	V_MultiplayerPeerExtension_GetConnectionStatus() MultiplayerPeerConnectionStatus
}

// OpenXRSpatialCapabilityConfigurationBaseHeaderVirtuals declares the Category-A virtual surface of Godot class OpenXRSpatialCapabilityConfigurationBaseHeader.
type OpenXRSpatialCapabilityConfigurationBaseHeaderVirtuals interface {
	V_OpenXRSpatialCapabilityConfigurationBaseHeader_HasValidConfiguration() bool
	V_OpenXRSpatialCapabilityConfigurationBaseHeader_GetConfiguration() uint64
}

// OpenXRSpatialComponentDataVirtuals declares the Category-A virtual surface of Godot class OpenXRSpatialComponentData.
type OpenXRSpatialComponentDataVirtuals interface {
	V_OpenXRSpatialComponentData_GetComponentType() uint64
}

// PacketPeerExtensionVirtuals declares the Category-A virtual surface of Godot class PacketPeerExtension.
type PacketPeerExtensionVirtuals interface {
	V_PacketPeerExtension_GetPacket(r_buffer **uint8, r_buffer_size *Int32T) Error
	V_PacketPeerExtension_PutPacket(buffer *uint8, buffer_size int32) Error
	V_PacketPeerExtension_GetAvailablePacketCount() int32
}

// PhysicsDirectBodyState2DExtensionVirtuals declares the Category-A virtual surface of Godot class PhysicsDirectBodyState2DExtension.
type PhysicsDirectBodyState2DExtensionVirtuals interface {
	V_PhysicsDirectBodyState2DExtension_GetTotalGravity() Vector2
	V_PhysicsDirectBodyState2DExtension_GetTotalLinearDamp() float32
	V_PhysicsDirectBodyState2DExtension_GetTotalAngularDamp() float32
	V_PhysicsDirectBodyState2DExtension_GetCenterOfMass() Vector2
	V_PhysicsDirectBodyState2DExtension_GetCenterOfMassLocal() Vector2
	V_PhysicsDirectBodyState2DExtension_GetInverseMass() float32
	V_PhysicsDirectBodyState2DExtension_GetInverseInertia() float32
	V_PhysicsDirectBodyState2DExtension_GetLinearVelocity() Vector2
	V_PhysicsDirectBodyState2DExtension_GetAngularVelocity() float32
	V_PhysicsDirectBodyState2DExtension_GetTransform() Transform2D
	V_PhysicsDirectBodyState2DExtension_GetVelocityAtLocalPosition(local_position Vector2) Vector2
	V_PhysicsDirectBodyState2DExtension_GetConstantForce() Vector2
	V_PhysicsDirectBodyState2DExtension_GetConstantTorque() float32
	V_PhysicsDirectBodyState2DExtension_IsSleeping() bool
	V_PhysicsDirectBodyState2DExtension_GetCollisionLayer() uint32
	V_PhysicsDirectBodyState2DExtension_GetCollisionMask() uint32
	V_PhysicsDirectBodyState2DExtension_GetContactCount() int32
	V_PhysicsDirectBodyState2DExtension_GetContactLocalPosition(contact_idx int32) Vector2
	V_PhysicsDirectBodyState2DExtension_GetContactLocalNormal(contact_idx int32) Vector2
	V_PhysicsDirectBodyState2DExtension_GetContactLocalShape(contact_idx int32) int32
	V_PhysicsDirectBodyState2DExtension_GetContactLocalVelocityAtPosition(contact_idx int32) Vector2
	V_PhysicsDirectBodyState2DExtension_GetContactCollider(contact_idx int32) RID
	V_PhysicsDirectBodyState2DExtension_GetContactColliderPosition(contact_idx int32) Vector2
	V_PhysicsDirectBodyState2DExtension_GetContactColliderId(contact_idx int32) uint64
	V_PhysicsDirectBodyState2DExtension_GetContactColliderObject(contact_idx int32) Object
	V_PhysicsDirectBodyState2DExtension_GetContactColliderShape(contact_idx int32) int32
	V_PhysicsDirectBodyState2DExtension_GetContactColliderVelocityAtPosition(contact_idx int32) Vector2
	V_PhysicsDirectBodyState2DExtension_GetContactImpulse(contact_idx int32) Vector2
	V_PhysicsDirectBodyState2DExtension_GetStep() float32
	V_PhysicsDirectBodyState2DExtension_GetSpaceState() PhysicsDirectSpaceState2D
}

// PhysicsDirectBodyState3DExtensionVirtuals declares the Category-A virtual surface of Godot class PhysicsDirectBodyState3DExtension.
type PhysicsDirectBodyState3DExtensionVirtuals interface {
	V_PhysicsDirectBodyState3DExtension_GetTotalGravity() Vector3
	V_PhysicsDirectBodyState3DExtension_GetTotalLinearDamp() float32
	V_PhysicsDirectBodyState3DExtension_GetTotalAngularDamp() float32
	V_PhysicsDirectBodyState3DExtension_GetCenterOfMass() Vector3
	V_PhysicsDirectBodyState3DExtension_GetCenterOfMassLocal() Vector3
	V_PhysicsDirectBodyState3DExtension_GetPrincipalInertiaAxes() Basis
	V_PhysicsDirectBodyState3DExtension_GetInverseMass() float32
	V_PhysicsDirectBodyState3DExtension_GetInverseInertia() Vector3
	V_PhysicsDirectBodyState3DExtension_GetInverseInertiaTensor() Basis
	V_PhysicsDirectBodyState3DExtension_GetLinearVelocity() Vector3
	V_PhysicsDirectBodyState3DExtension_GetAngularVelocity() Vector3
	V_PhysicsDirectBodyState3DExtension_GetTransform() Transform3D
	V_PhysicsDirectBodyState3DExtension_GetVelocityAtLocalPosition(local_position Vector3) Vector3
	V_PhysicsDirectBodyState3DExtension_GetConstantForce() Vector3
	V_PhysicsDirectBodyState3DExtension_GetConstantTorque() Vector3
	V_PhysicsDirectBodyState3DExtension_IsSleeping() bool
	V_PhysicsDirectBodyState3DExtension_GetCollisionLayer() uint32
	V_PhysicsDirectBodyState3DExtension_GetCollisionMask() uint32
	V_PhysicsDirectBodyState3DExtension_GetContactCount() int32
	V_PhysicsDirectBodyState3DExtension_GetContactLocalPosition(contact_idx int32) Vector3
	V_PhysicsDirectBodyState3DExtension_GetContactLocalNormal(contact_idx int32) Vector3
	V_PhysicsDirectBodyState3DExtension_GetContactImpulse(contact_idx int32) Vector3
	V_PhysicsDirectBodyState3DExtension_GetContactLocalShape(contact_idx int32) int32
	V_PhysicsDirectBodyState3DExtension_GetContactLocalVelocityAtPosition(contact_idx int32) Vector3
	V_PhysicsDirectBodyState3DExtension_GetContactCollider(contact_idx int32) RID
	V_PhysicsDirectBodyState3DExtension_GetContactColliderPosition(contact_idx int32) Vector3
	V_PhysicsDirectBodyState3DExtension_GetContactColliderId(contact_idx int32) uint64
	V_PhysicsDirectBodyState3DExtension_GetContactColliderObject(contact_idx int32) Object
	V_PhysicsDirectBodyState3DExtension_GetContactColliderShape(contact_idx int32) int32
	V_PhysicsDirectBodyState3DExtension_GetContactColliderVelocityAtPosition(contact_idx int32) Vector3
	V_PhysicsDirectBodyState3DExtension_GetStep() float32
	V_PhysicsDirectBodyState3DExtension_GetSpaceState() PhysicsDirectSpaceState3D
}

// PhysicsDirectSpaceState2DExtensionVirtuals declares the Category-A virtual surface of Godot class PhysicsDirectSpaceState2DExtension.
type PhysicsDirectSpaceState2DExtensionVirtuals interface {
	V_PhysicsDirectSpaceState2DExtension_IntersectRay(from Vector2, to Vector2, collision_mask uint32, collide_with_bodies bool, collide_with_areas bool, hit_from_inside bool, r_result *PhysicsServer2DExtensionRayResult) bool
	V_PhysicsDirectSpaceState2DExtension_IntersectPoint(position Vector2, canvas_instance_id uint64, collision_mask uint32, collide_with_bodies bool, collide_with_areas bool, r_results *PhysicsServer2DExtensionShapeResult, max_results int32) int32
	V_PhysicsDirectSpaceState2DExtension_IntersectShape(shape_rid RID, transform Transform2D, motion Vector2, margin float32, collision_mask uint32, collide_with_bodies bool, collide_with_areas bool, r_result *PhysicsServer2DExtensionShapeResult, max_results int32) int32
	V_PhysicsDirectSpaceState2DExtension_CastMotion(shape_rid RID, transform Transform2D, motion Vector2, margin float32, collision_mask uint32, collide_with_bodies bool, collide_with_areas bool, r_closest_safe *float32, r_closest_unsafe *float32) bool
	V_PhysicsDirectSpaceState2DExtension_CollideShape(shape_rid RID, transform Transform2D, motion Vector2, margin float32, collision_mask uint32, collide_with_bodies bool, collide_with_areas bool, r_results unsafe.Pointer, max_results int32, r_result_count *Int32T) bool
}

// PhysicsDirectSpaceState3DExtensionVirtuals declares the Category-A virtual surface of Godot class PhysicsDirectSpaceState3DExtension.
type PhysicsDirectSpaceState3DExtensionVirtuals interface {
	V_PhysicsDirectSpaceState3DExtension_IntersectRay(from Vector3, to Vector3, collision_mask uint32, collide_with_bodies bool, collide_with_areas bool, hit_from_inside bool, hit_back_faces bool, pick_ray bool, r_result *PhysicsServer3DExtensionRayResult) bool
	V_PhysicsDirectSpaceState3DExtension_IntersectPoint(position Vector3, collision_mask uint32, collide_with_bodies bool, collide_with_areas bool, r_results *PhysicsServer3DExtensionShapeResult, max_results int32) int32
	V_PhysicsDirectSpaceState3DExtension_IntersectShape(shape_rid RID, transform Transform3D, motion Vector3, margin float32, collision_mask uint32, collide_with_bodies bool, collide_with_areas bool, r_result_count *PhysicsServer3DExtensionShapeResult, max_results int32) int32
	V_PhysicsDirectSpaceState3DExtension_CastMotion(shape_rid RID, transform Transform3D, motion Vector3, margin float32, collision_mask uint32, collide_with_bodies bool, collide_with_areas bool, r_closest_safe *float32, r_closest_unsafe *float32, r_info *PhysicsServer3DExtensionShapeRestInfo) bool
	V_PhysicsDirectSpaceState3DExtension_CollideShape(shape_rid RID, transform Transform3D, motion Vector3, margin float32, collision_mask uint32, collide_with_bodies bool, collide_with_areas bool, r_results unsafe.Pointer, max_results int32, r_result_count *Int32T) bool
}

// PhysicsServer2DExtensionVirtuals declares the Category-A virtual surface of Godot class PhysicsServer2DExtension.
type PhysicsServer2DExtensionVirtuals interface {
	V_PhysicsServer2DExtension_WorldBoundaryShapeCreate() RID
	V_PhysicsServer2DExtension_SeparationRayShapeCreate() RID
	V_PhysicsServer2DExtension_SegmentShapeCreate() RID
	V_PhysicsServer2DExtension_CircleShapeCreate() RID
	V_PhysicsServer2DExtension_RectangleShapeCreate() RID
	V_PhysicsServer2DExtension_CapsuleShapeCreate() RID
	V_PhysicsServer2DExtension_ConvexPolygonShapeCreate() RID
	V_PhysicsServer2DExtension_ConcavePolygonShapeCreate() RID
	V_PhysicsServer2DExtension_ShapeGetType(shape RID) PhysicsServer2DShapeType
	V_PhysicsServer2DExtension_ShapeGetData(shape RID) Variant
	V_PhysicsServer2DExtension_SpaceCreate() RID
	V_PhysicsServer2DExtension_SpaceIsActive(space RID) bool
	V_PhysicsServer2DExtension_SpaceGetParam(space RID, param PhysicsServer2DSpaceParameter) float32
	V_PhysicsServer2DExtension_SpaceGetDirectState(space RID) PhysicsDirectSpaceState2D
	V_PhysicsServer2DExtension_AreaCreate() RID
	V_PhysicsServer2DExtension_AreaGetSpace(area RID) RID
	V_PhysicsServer2DExtension_AreaGetShapeCount(area RID) int32
	V_PhysicsServer2DExtension_AreaGetShape(area RID, shape_idx int32) RID
	V_PhysicsServer2DExtension_AreaGetShapeTransform(area RID, shape_idx int32) Transform2D
	V_PhysicsServer2DExtension_AreaGetObjectInstanceId(area RID) uint64
	V_PhysicsServer2DExtension_AreaGetCanvasInstanceId(area RID) uint64
	V_PhysicsServer2DExtension_AreaGetParam(area RID, param PhysicsServer2DAreaParameter) Variant
	V_PhysicsServer2DExtension_AreaGetTransform(area RID) Transform2D
	V_PhysicsServer2DExtension_AreaGetCollisionLayer(area RID) uint32
	V_PhysicsServer2DExtension_AreaGetCollisionMask(area RID) uint32
	V_PhysicsServer2DExtension_BodyCreate() RID
	V_PhysicsServer2DExtension_BodyGetSpace(body RID) RID
	V_PhysicsServer2DExtension_BodyGetMode(body RID) PhysicsServer2DBodyMode
	V_PhysicsServer2DExtension_BodyGetShapeCount(body RID) int32
	V_PhysicsServer2DExtension_BodyGetShape(body RID, shape_idx int32) RID
	V_PhysicsServer2DExtension_BodyGetShapeTransform(body RID, shape_idx int32) Transform2D
	V_PhysicsServer2DExtension_BodyGetObjectInstanceId(body RID) uint64
	V_PhysicsServer2DExtension_BodyGetCanvasInstanceId(body RID) uint64
	V_PhysicsServer2DExtension_BodyGetContinuousCollisionDetectionMode(body RID) PhysicsServer2DCCDMode
	V_PhysicsServer2DExtension_BodyGetCollisionLayer(body RID) uint32
	V_PhysicsServer2DExtension_BodyGetCollisionMask(body RID) uint32
	V_PhysicsServer2DExtension_BodyGetCollisionPriority(body RID) float32
	V_PhysicsServer2DExtension_BodyGetParam(body RID, param PhysicsServer2DBodyParameter) Variant
	V_PhysicsServer2DExtension_BodyGetState(body RID, state PhysicsServer2DBodyState) Variant
	V_PhysicsServer2DExtension_BodyGetConstantForce(body RID) Vector2
	V_PhysicsServer2DExtension_BodyGetConstantTorque(body RID) float32
	V_PhysicsServer2DExtension_BodyGetMaxContactsReported(body RID) int32
	V_PhysicsServer2DExtension_BodyIsOmittingForceIntegration(body RID) bool
	V_PhysicsServer2DExtension_BodyGetDirectState(body RID) PhysicsDirectBodyState2D
	V_PhysicsServer2DExtension_BodyTestMotion(body RID, from Transform2D, motion Vector2, margin float32, collide_separation_ray bool, recovery_as_collision bool, r_result *PhysicsServer2DExtensionMotionResult) bool
	V_PhysicsServer2DExtension_JointCreate() RID
	V_PhysicsServer2DExtension_JointGetParam(joint RID, param PhysicsServer2DJointParam) float32
	V_PhysicsServer2DExtension_JointIsDisabledCollisionsBetweenBodies(joint RID) bool
	V_PhysicsServer2DExtension_PinJointGetFlag(joint RID, flag PhysicsServer2DPinJointFlag) bool
	V_PhysicsServer2DExtension_PinJointGetParam(joint RID, param PhysicsServer2DPinJointParam) float32
	V_PhysicsServer2DExtension_DampedSpringJointGetParam(joint RID, param PhysicsServer2DDampedSpringParam) float32
	V_PhysicsServer2DExtension_JointGetType(joint RID) PhysicsServer2DJointType
	V_PhysicsServer2DExtension_GetProcessInfo(process_info PhysicsServer2DProcessInfo) int32
}

// PhysicsServer3DExtensionVirtuals declares the Category-A virtual surface of Godot class PhysicsServer3DExtension.
type PhysicsServer3DExtensionVirtuals interface {
	V_PhysicsServer3DExtension_WorldBoundaryShapeCreate() RID
	V_PhysicsServer3DExtension_SeparationRayShapeCreate() RID
	V_PhysicsServer3DExtension_SphereShapeCreate() RID
	V_PhysicsServer3DExtension_BoxShapeCreate() RID
	V_PhysicsServer3DExtension_CapsuleShapeCreate() RID
	V_PhysicsServer3DExtension_CylinderShapeCreate() RID
	V_PhysicsServer3DExtension_ConvexPolygonShapeCreate() RID
	V_PhysicsServer3DExtension_ConcavePolygonShapeCreate() RID
	V_PhysicsServer3DExtension_HeightmapShapeCreate() RID
	V_PhysicsServer3DExtension_CustomShapeCreate() RID
	V_PhysicsServer3DExtension_ShapeGetMargin(shape RID) float32
	V_PhysicsServer3DExtension_ShapeGetType(shape RID) PhysicsServer3DShapeType
	V_PhysicsServer3DExtension_ShapeGetData(shape RID) Variant
	V_PhysicsServer3DExtension_SpaceCreate() RID
	V_PhysicsServer3DExtension_SpaceIsActive(space RID) bool
	V_PhysicsServer3DExtension_SpaceGetParam(space RID, param PhysicsServer3DSpaceParameter) float32
	V_PhysicsServer3DExtension_SpaceGetDirectState(space RID) PhysicsDirectSpaceState3D
	V_PhysicsServer3DExtension_AreaCreate() RID
	V_PhysicsServer3DExtension_AreaGetSpace(area RID) RID
	V_PhysicsServer3DExtension_AreaGetShapeCount(area RID) int32
	V_PhysicsServer3DExtension_AreaGetShape(area RID, shape_idx int32) RID
	V_PhysicsServer3DExtension_AreaGetShapeTransform(area RID, shape_idx int32) Transform3D
	V_PhysicsServer3DExtension_AreaGetObjectInstanceId(area RID) uint64
	V_PhysicsServer3DExtension_AreaGetParam(area RID, param PhysicsServer3DAreaParameter) Variant
	V_PhysicsServer3DExtension_AreaGetTransform(area RID) Transform3D
	V_PhysicsServer3DExtension_AreaGetCollisionLayer(area RID) uint32
	V_PhysicsServer3DExtension_AreaGetCollisionMask(area RID) uint32
	V_PhysicsServer3DExtension_BodyCreate() RID
	V_PhysicsServer3DExtension_BodyGetSpace(body RID) RID
	V_PhysicsServer3DExtension_BodyGetMode(body RID) PhysicsServer3DBodyMode
	V_PhysicsServer3DExtension_BodyGetShapeCount(body RID) int32
	V_PhysicsServer3DExtension_BodyGetShape(body RID, shape_idx int32) RID
	V_PhysicsServer3DExtension_BodyGetShapeTransform(body RID, shape_idx int32) Transform3D
	V_PhysicsServer3DExtension_BodyGetObjectInstanceId(body RID) uint64
	V_PhysicsServer3DExtension_BodyIsContinuousCollisionDetectionEnabled(body RID) bool
	V_PhysicsServer3DExtension_BodyGetCollisionLayer(body RID) uint32
	V_PhysicsServer3DExtension_BodyGetCollisionMask(body RID) uint32
	V_PhysicsServer3DExtension_BodyGetCollisionPriority(body RID) float32
	V_PhysicsServer3DExtension_BodyGetParam(body RID, param PhysicsServer3DBodyParameter) Variant
	V_PhysicsServer3DExtension_BodyGetState(body RID, state PhysicsServer3DBodyState) Variant
	V_PhysicsServer3DExtension_BodyGetConstantForce(body RID) Vector3
	V_PhysicsServer3DExtension_BodyGetConstantTorque(body RID) Vector3
	V_PhysicsServer3DExtension_BodyIsAxisLocked(body RID, axis PhysicsServer3DBodyAxis) bool
	V_PhysicsServer3DExtension_BodyGetMaxContactsReported(body RID) int32
	V_PhysicsServer3DExtension_BodyIsOmittingForceIntegration(body RID) bool
	V_PhysicsServer3DExtension_BodyTestMotion(body RID, from Transform3D, motion Vector3, margin float32, max_collisions int32, collide_separation_ray bool, recovery_as_collision bool, r_result *PhysicsServer3DExtensionMotionResult) bool
	V_PhysicsServer3DExtension_BodyGetDirectState(body RID) PhysicsDirectBodyState3D
	V_PhysicsServer3DExtension_SoftBodyCreate() RID
	V_PhysicsServer3DExtension_SoftBodyGetSpace(body RID) RID
	V_PhysicsServer3DExtension_SoftBodyGetCollisionLayer(body RID) uint32
	V_PhysicsServer3DExtension_SoftBodyGetCollisionMask(body RID) uint32
	V_PhysicsServer3DExtension_SoftBodyGetState(body RID, state PhysicsServer3DBodyState) Variant
	V_PhysicsServer3DExtension_SoftBodyGetSimulationPrecision(body RID) int32
	V_PhysicsServer3DExtension_SoftBodyGetTotalMass(body RID) float32
	V_PhysicsServer3DExtension_SoftBodyGetLinearStiffness(body RID) float32
	V_PhysicsServer3DExtension_SoftBodyGetShrinkingFactor(body RID) float32
	V_PhysicsServer3DExtension_SoftBodyGetPressureCoefficient(body RID) float32
	V_PhysicsServer3DExtension_SoftBodyGetDampingCoefficient(body RID) float32
	V_PhysicsServer3DExtension_SoftBodyGetDragCoefficient(body RID) float32
	V_PhysicsServer3DExtension_SoftBodyGetBounds(body RID) AABB
	V_PhysicsServer3DExtension_SoftBodyGetPointGlobalPosition(body RID, point_index int32) Vector3
	V_PhysicsServer3DExtension_SoftBodyIsPointPinned(body RID, point_index int32) bool
	V_PhysicsServer3DExtension_JointCreate() RID
	V_PhysicsServer3DExtension_PinJointGetParam(joint RID, param PhysicsServer3DPinJointParam) float32
	V_PhysicsServer3DExtension_PinJointGetLocalA(joint RID) Vector3
	V_PhysicsServer3DExtension_PinJointGetLocalB(joint RID) Vector3
	V_PhysicsServer3DExtension_HingeJointGetParam(joint RID, param PhysicsServer3DHingeJointParam) float32
	V_PhysicsServer3DExtension_HingeJointGetFlag(joint RID, flag PhysicsServer3DHingeJointFlag) bool
	V_PhysicsServer3DExtension_SliderJointGetParam(joint RID, param PhysicsServer3DSliderJointParam) float32
	V_PhysicsServer3DExtension_ConeTwistJointGetParam(joint RID, param PhysicsServer3DConeTwistJointParam) float32
	V_PhysicsServer3DExtension_Generic6DofJointGetParam(joint RID, axis Vector3Axis, param PhysicsServer3DG6DOFJointAxisParam) float32
	V_PhysicsServer3DExtension_Generic6DofJointGetFlag(joint RID, axis Vector3Axis, flag PhysicsServer3DG6DOFJointAxisFlag) bool
	V_PhysicsServer3DExtension_JointGetType(joint RID) PhysicsServer3DJointType
	V_PhysicsServer3DExtension_JointGetSolverPriority(joint RID) int32
	V_PhysicsServer3DExtension_JointIsDisabledCollisionsBetweenBodies(joint RID) bool
	V_PhysicsServer3DExtension_GetProcessInfo(process_info PhysicsServer3DProcessInfo) int32
}

// RenderDataExtensionVirtuals declares the Category-A virtual surface of Godot class RenderDataExtension.
type RenderDataExtensionVirtuals interface {
	V_RenderDataExtension_GetRenderSceneBuffers() RefRenderSceneBuffers
	V_RenderDataExtension_GetRenderSceneData() RenderSceneData
	V_RenderDataExtension_GetEnvironment() RID
	V_RenderDataExtension_GetCameraAttributes() RID
}

// RenderSceneDataExtensionVirtuals declares the Category-A virtual surface of Godot class RenderSceneDataExtension.
type RenderSceneDataExtensionVirtuals interface {
	V_RenderSceneDataExtension_GetCamTransform() Transform3D
	V_RenderSceneDataExtension_GetCamProjection() Projection
	V_RenderSceneDataExtension_GetViewCount() uint32
	V_RenderSceneDataExtension_GetViewEyeOffset(view uint32) Vector3
	V_RenderSceneDataExtension_GetViewProjection(view uint32) Projection
	V_RenderSceneDataExtension_GetUniformBuffer() RID
}

// ResourceVirtuals declares the Category-A virtual surface of Godot class Resource.
type ResourceVirtuals interface {
	V_Resource_GetRid() RID
}

// ScriptExtensionVirtuals declares the Category-A virtual surface of Godot class ScriptExtension.
type ScriptExtensionVirtuals interface {
	V_ScriptExtension_CanInstantiate() bool
	V_ScriptExtension_GetBaseScript() RefScript
	V_ScriptExtension_GetGlobalName() StringName
	V_ScriptExtension_GetInstanceBaseType() StringName
	V_ScriptExtension_HasSourceCode() bool
	V_ScriptExtension_GetSourceCode() String
	V_ScriptExtension_Reload(keep_state bool) Error
	V_ScriptExtension_HasMethod(method StringName) bool
	V_ScriptExtension_IsTool() bool
	V_ScriptExtension_IsAbstract() bool
	V_ScriptExtension_HasScriptSignal(signal StringName) bool
	V_ScriptExtension_GetScriptSignalList() Dictionary
	V_ScriptExtension_GetPropertyDefaultValue(property StringName) Variant
	V_ScriptExtension_GetScriptMethodList() Dictionary
	V_ScriptExtension_GetScriptPropertyList() Dictionary
	V_ScriptExtension_GetRpcConfig() Variant
	V_ScriptExtension_InstanceHas(object Object) bool
}

// StreamPeerExtensionVirtuals declares the Category-A virtual surface of Godot class StreamPeerExtension.
type StreamPeerExtensionVirtuals interface {
	V_StreamPeerExtension_GetData(r_buffer *uint8, r_bytes int32, r_received *Int32T) Error
	V_StreamPeerExtension_GetPartialData(r_buffer *uint8, r_bytes int32, r_received *Int32T) Error
	V_StreamPeerExtension_PutData(data *uint8, bytes int32, r_sent *Int32T) Error
	V_StreamPeerExtension_PutPartialData(data *uint8, bytes int32, r_sent *Int32T) Error
	V_StreamPeerExtension_GetAvailableBytes() int32
}

// StyleBoxVirtuals declares the Category-A virtual surface of Godot class StyleBox.
type StyleBoxVirtuals interface {
	V_StyleBox_GetMinimumSize() Vector2
	V_StyleBox_TestMask(point Vector2, rect Rect2) bool
}

// SyntaxHighlighterVirtuals declares the Category-A virtual surface of Godot class SyntaxHighlighter.
type SyntaxHighlighterVirtuals interface {
	V_SyntaxHighlighter_GetLineSyntaxHighlighting(line int32) Dictionary
}

// TextServerExtensionVirtuals declares the Category-A virtual surface of Godot class TextServerExtension.
type TextServerExtensionVirtuals interface {
	V_TextServerExtension_HasFeature(feature TextServerFeature) bool
	V_TextServerExtension_GetName() String
	V_TextServerExtension_GetFeatures() int64
	V_TextServerExtension_Has(rid RID) bool
	V_TextServerExtension_LoadSupportData(filename String) bool
	V_TextServerExtension_GetSupportDataFilename() String
	V_TextServerExtension_GetSupportDataInfo() String
	V_TextServerExtension_SaveSupportData(filename String) bool
	V_TextServerExtension_GetSupportData() PackedByteArray
	V_TextServerExtension_IsLocaleUsingSupportData(locale String) bool
	V_TextServerExtension_IsLocaleRightToLeft(locale String) bool
	V_TextServerExtension_NameToTag(name String) int64
	V_TextServerExtension_TagToName(tag int64) String
	V_TextServerExtension_CreateFont() RID
	V_TextServerExtension_CreateFontLinkedVariation(font_rid RID) RID
	V_TextServerExtension_FontGetFaceIndex(font_rid RID) int64
	V_TextServerExtension_FontGetFaceCount(font_rid RID) int64
	V_TextServerExtension_FontGetStyle(font_rid RID) TextServerFontStyle
	V_TextServerExtension_FontGetName(font_rid RID) String
	V_TextServerExtension_FontGetOtNameStrings(font_rid RID) Dictionary
	V_TextServerExtension_FontGetStyleName(font_rid RID) String
	V_TextServerExtension_FontGetWeight(font_rid RID) int64
	V_TextServerExtension_FontGetStretch(font_rid RID) int64
	V_TextServerExtension_FontGetAntialiasing(font_rid RID) TextServerFontAntialiasing
	V_TextServerExtension_FontGetDisableEmbeddedBitmaps(font_rid RID) bool
	V_TextServerExtension_FontGetGenerateMipmaps(font_rid RID) bool
	V_TextServerExtension_FontIsMultichannelSignedDistanceField(font_rid RID) bool
	V_TextServerExtension_FontGetMsdfPixelRange(font_rid RID) int64
	V_TextServerExtension_FontGetMsdfSize(font_rid RID) int64
	V_TextServerExtension_FontGetFixedSize(font_rid RID) int64
	V_TextServerExtension_FontGetFixedSizeScaleMode(font_rid RID) TextServerFixedSizeScaleMode
	V_TextServerExtension_FontIsAllowSystemFallback(font_rid RID) bool
	V_TextServerExtension_FontIsForceAutohinter(font_rid RID) bool
	V_TextServerExtension_FontIsModulateColorGlyphs(font_rid RID) bool
	V_TextServerExtension_FontGetPaletteCount(font_rid RID) int64
	V_TextServerExtension_FontGetPaletteName(font_rid RID, index int64) String
	V_TextServerExtension_FontGetPaletteColors(font_rid RID, index int64) PackedColorArray
	V_TextServerExtension_FontGetPaletteCustomColors(font_rid RID) PackedColorArray
	V_TextServerExtension_FontGetUsedPalette(font_rid RID) int64
	V_TextServerExtension_FontGetHinting(font_rid RID) TextServerHinting
	V_TextServerExtension_FontGetSubpixelPositioning(font_rid RID) TextServerSubpixelPositioning
	V_TextServerExtension_FontGetKeepRoundingRemainders(font_rid RID) bool
	V_TextServerExtension_FontGetEmbolden(font_rid RID) float64
	V_TextServerExtension_FontGetSpacing(font_rid RID, spacing TextServerSpacingType) int64
	V_TextServerExtension_FontGetBaselineOffset(font_rid RID) float64
	V_TextServerExtension_FontGetTransform(font_rid RID) Transform2D
	V_TextServerExtension_FontGetVariationCoordinates(font_rid RID) Dictionary
	V_TextServerExtension_FontGetOversampling(font_rid RID) float64
	V_TextServerExtension_FontGetSizeCacheList(font_rid RID) Vector2i
	V_TextServerExtension_FontGetSizeCacheInfo(font_rid RID) Dictionary
	V_TextServerExtension_FontGetAscent(font_rid RID, size int64) float64
	V_TextServerExtension_FontGetDescent(font_rid RID, size int64) float64
	V_TextServerExtension_FontGetUnderlinePosition(font_rid RID, size int64) float64
	V_TextServerExtension_FontGetUnderlineThickness(font_rid RID, size int64) float64
	V_TextServerExtension_FontGetScale(font_rid RID, size int64) float64
	V_TextServerExtension_FontGetTextureCount(font_rid RID, size Vector2i) int64
	V_TextServerExtension_FontGetTextureImage(font_rid RID, size Vector2i, texture_index int64) RefImage
	V_TextServerExtension_FontGetTextureOffsets(font_rid RID, size Vector2i, texture_index int64) PackedInt32Array
	V_TextServerExtension_FontGetGlyphList(font_rid RID, size Vector2i) PackedInt32Array
	V_TextServerExtension_FontGetGlyphAdvance(font_rid RID, size int64, glyph int64) Vector2
	V_TextServerExtension_FontGetGlyphOffset(font_rid RID, size Vector2i, glyph int64) Vector2
	V_TextServerExtension_FontGetGlyphSize(font_rid RID, size Vector2i, glyph int64) Vector2
	V_TextServerExtension_FontGetGlyphUvRect(font_rid RID, size Vector2i, glyph int64) Rect2
	V_TextServerExtension_FontGetGlyphTextureIdx(font_rid RID, size Vector2i, glyph int64) int64
	V_TextServerExtension_FontGetGlyphTextureRid(font_rid RID, size Vector2i, glyph int64) RID
	V_TextServerExtension_FontGetGlyphTextureSize(font_rid RID, size Vector2i, glyph int64) Vector2
	V_TextServerExtension_FontGetGlyphContours(font_rid RID, size int64, index int64) Dictionary
	V_TextServerExtension_FontGetKerningList(font_rid RID, size int64) Vector2i
	V_TextServerExtension_FontGetKerning(font_rid RID, size int64, glyph_pair Vector2i) Vector2
	V_TextServerExtension_FontGetGlyphIndex(font_rid RID, size int64, char int64, variation_selector int64) int64
	V_TextServerExtension_FontGetCharFromGlyphIndex(font_rid RID, size int64, glyph_index int64) int64
	V_TextServerExtension_FontHasChar(font_rid RID, char int64) bool
	V_TextServerExtension_FontGetSupportedChars(font_rid RID) String
	V_TextServerExtension_FontGetSupportedGlyphs(font_rid RID) PackedInt32Array
	V_TextServerExtension_FontIsLanguageSupported(font_rid RID, language String) bool
	V_TextServerExtension_FontGetLanguageSupportOverride(font_rid RID, language String) bool
	V_TextServerExtension_FontGetLanguageSupportOverrides(font_rid RID) PackedStringArray
	V_TextServerExtension_FontIsScriptSupported(font_rid RID, script String) bool
	V_TextServerExtension_FontGetScriptSupportOverride(font_rid RID, script String) bool
	V_TextServerExtension_FontGetScriptSupportOverrides(font_rid RID) PackedStringArray
	V_TextServerExtension_FontGetOpentypeFeatureOverrides(font_rid RID) Dictionary
	V_TextServerExtension_FontSupportedFeatureList(font_rid RID) Dictionary
	V_TextServerExtension_FontSupportedVariationList(font_rid RID) Dictionary
	V_TextServerExtension_FontGetGlobalOversampling() float64
	V_TextServerExtension_GetHexCodeBoxSize(size int64, index int64) Vector2
	V_TextServerExtension_CreateShapedText(direction TextServerDirection, orientation TextServerOrientation) RID
	V_TextServerExtension_ShapedTextDuplicate(shaped RID) RID
	V_TextServerExtension_ShapedTextGetDirection(shaped RID) TextServerDirection
	V_TextServerExtension_ShapedTextGetInferredDirection(shaped RID) TextServerDirection
	V_TextServerExtension_ShapedTextGetCustomPunctuation(shaped RID) String
	V_TextServerExtension_ShapedTextGetCustomEllipsis(shaped RID) int64
	V_TextServerExtension_ShapedTextGetOrientation(shaped RID) TextServerOrientation
	V_TextServerExtension_ShapedTextGetPreserveInvalid(shaped RID) bool
	V_TextServerExtension_ShapedTextGetPreserveControl(shaped RID) bool
	V_TextServerExtension_ShapedTextGetSpacing(shaped RID, spacing TextServerSpacingType) int64
	V_TextServerExtension_ShapedTextAddString(shaped RID, text String, fonts RID, size int64, opentype_features Dictionary, language String, meta Variant) bool
	V_TextServerExtension_ShapedTextAddObject(shaped RID, key Variant, size Vector2, inline_align InlineAlignment, length int64, baseline float64) bool
	V_TextServerExtension_ShapedTextResizeObject(shaped RID, key Variant, size Vector2, inline_align InlineAlignment, baseline float64) bool
	V_TextServerExtension_ShapedTextHasObject(shaped RID, key Variant) bool
	V_TextServerExtension_ShapedGetText(shaped RID) String
	V_TextServerExtension_ShapedGetSpanCount(shaped RID) int64
	V_TextServerExtension_ShapedGetSpanMeta(shaped RID, index int64) Variant
	V_TextServerExtension_ShapedGetSpanEmbeddedObject(shaped RID, index int64) Variant
	V_TextServerExtension_ShapedGetSpanText(shaped RID, index int64) String
	V_TextServerExtension_ShapedGetSpanObject(shaped RID, index int64) Variant
	V_TextServerExtension_ShapedGetRunCount(shaped RID) int64
	V_TextServerExtension_ShapedGetRunText(shaped RID, index int64) String
	V_TextServerExtension_ShapedGetRunRange(shaped RID, index int64) Vector2i
	V_TextServerExtension_ShapedGetRunGlyphRange(shaped RID, index int64) Vector2i
	V_TextServerExtension_ShapedGetRunFontRid(shaped RID, index int64) RID
	V_TextServerExtension_ShapedGetRunFontSize(shaped RID, index int64) int32
	V_TextServerExtension_ShapedGetRunLanguage(shaped RID, index int64) String
	V_TextServerExtension_ShapedGetRunDirection(shaped RID, index int64) TextServerDirection
	V_TextServerExtension_ShapedGetRunObject(shaped RID, index int64) Variant
	V_TextServerExtension_ShapedTextSubstr(shaped RID, start int64, length int64) RID
	V_TextServerExtension_ShapedTextGetParent(shaped RID) RID
	V_TextServerExtension_ShapedTextFitToWidth(shaped RID, width float64, justification_flags TextServerJustificationFlag) float64
	V_TextServerExtension_ShapedTextTabAlign(shaped RID, tab_stops PackedFloat32Array) float64
	V_TextServerExtension_ShapedTextShape(shaped RID) bool
	V_TextServerExtension_ShapedTextIsReady(shaped RID) bool
	V_TextServerExtension_ShapedTextGetGlyphs(shaped RID) *Glyph
	V_TextServerExtension_ShapedTextSortLogical(shaped RID) *Glyph
	V_TextServerExtension_ShapedTextGetGlyphCount(shaped RID) int64
	V_TextServerExtension_ShapedTextGetRange(shaped RID) Vector2i
	V_TextServerExtension_ShapedTextGetLineBreaksAdv(shaped RID, width PackedFloat32Array, start int64, once bool, break_flags TextServerLineBreakFlag) PackedInt32Array
	V_TextServerExtension_ShapedTextGetLineBreaks(shaped RID, width float64, start int64, break_flags TextServerLineBreakFlag) PackedInt32Array
	V_TextServerExtension_ShapedTextGetWordBreaks(shaped RID, grapheme_flags TextServerGraphemeFlag, skip_grapheme_flags TextServerGraphemeFlag) PackedInt32Array
	V_TextServerExtension_ShapedTextGetTrimPos(shaped RID) int64
	V_TextServerExtension_ShapedTextGetEllipsisPos(shaped RID) int64
	V_TextServerExtension_ShapedTextGetEllipsisGlyphCount(shaped RID) int64
	V_TextServerExtension_ShapedTextGetEllipsisGlyphs(shaped RID) *Glyph
	V_TextServerExtension_ShapedTextGetObjects(shaped RID) Array
	V_TextServerExtension_ShapedTextGetObjectRect(shaped RID, key Variant) Rect2
	V_TextServerExtension_ShapedTextGetObjectRange(shaped RID, key Variant) Vector2i
	V_TextServerExtension_ShapedTextGetObjectGlyph(shaped RID, key Variant) int64
	V_TextServerExtension_ShapedTextGetSize(shaped RID) Vector2
	V_TextServerExtension_ShapedTextGetAscent(shaped RID) float64
	V_TextServerExtension_ShapedTextGetDescent(shaped RID) float64
	V_TextServerExtension_ShapedTextGetWidth(shaped RID) float64
	V_TextServerExtension_ShapedTextGetUnderlinePosition(shaped RID) float64
	V_TextServerExtension_ShapedTextGetUnderlineThickness(shaped RID) float64
	V_TextServerExtension_ShapedTextGetDominantDirectionInRange(shaped RID, start int64, end int64) int64
	V_TextServerExtension_ShapedTextGetSelection(shaped RID, start int64, end int64) PackedVector2Array
	V_TextServerExtension_ShapedTextHitTestGrapheme(shaped RID, coord float64) int64
	V_TextServerExtension_ShapedTextHitTestPosition(shaped RID, coord float64) int64
	V_TextServerExtension_ShapedTextGetGraphemeBounds(shaped RID, pos int64) Vector2
	V_TextServerExtension_ShapedTextNextGraphemePos(shaped RID, pos int64) int64
	V_TextServerExtension_ShapedTextPrevGraphemePos(shaped RID, pos int64) int64
	V_TextServerExtension_ShapedTextGetCharacterBreaks(shaped RID) PackedInt32Array
	V_TextServerExtension_ShapedTextNextCharacterPos(shaped RID, pos int64) int64
	V_TextServerExtension_ShapedTextPrevCharacterPos(shaped RID, pos int64) int64
	V_TextServerExtension_ShapedTextClosestCharacterPos(shaped RID, pos int64) int64
	V_TextServerExtension_FormatNumber(number String, language String) String
	V_TextServerExtension_ParseNumber(number String, language String) String
	V_TextServerExtension_PercentSign(language String) String
	V_TextServerExtension_StripDiacritics(strValue String) String
	V_TextServerExtension_IsValidIdentifier(strValue String) bool
	V_TextServerExtension_IsValidLetter(unicode uint64) bool
	V_TextServerExtension_StringGetWordBreaks(strValue String, language String, chars_per_line int64) PackedInt32Array
	V_TextServerExtension_StringGetCharacterBreaks(strValue String, language String) PackedInt32Array
	V_TextServerExtension_IsConfusable(strValue String, dict PackedStringArray) int64
	V_TextServerExtension_SpoofCheck(strValue String) bool
	V_TextServerExtension_StringToUpper(strValue String, language String) String
	V_TextServerExtension_StringToLower(strValue String, language String) String
	V_TextServerExtension_StringToTitle(strValue String, language String) String
	V_TextServerExtension_ParseStructuredText(parser_type TextServerStructuredTextParser, args Array, text String) Vector3i
}

// Texture2DVirtuals declares the Category-A virtual surface of Godot class Texture2D.
type Texture2DVirtuals interface {
	V_Texture2D_GetImage() RefImage
	V_Texture2D_GetFormat() ImageFormat
	V_Texture2D_GetMipmapCount() int32
	V_Texture2D_GetWidth() int32
	V_Texture2D_GetHeight() int32
	V_Texture2D_HasAlpha() bool
	V_Texture2D_HasMipmaps() bool
}

// Texture3DVirtuals declares the Category-A virtual surface of Godot class Texture3D.
type Texture3DVirtuals interface {
	V_Texture3D_GetFormat() ImageFormat
	V_Texture3D_GetWidth() int32
	V_Texture3D_GetHeight() int32
	V_Texture3D_GetDepth() int32
	V_Texture3D_HasMipmaps() bool
	V_Texture3D_GetData() RefImage
}

// TextureLayeredVirtuals declares the Category-A virtual surface of Godot class TextureLayered.
type TextureLayeredVirtuals interface {
	V_TextureLayered_GetFormat() ImageFormat
	V_TextureLayered_GetLayeredType() uint32
	V_TextureLayered_GetWidth() int32
	V_TextureLayered_GetHeight() int32
	V_TextureLayered_GetLayers() int32
	V_TextureLayered_HasMipmaps() bool
	V_TextureLayered_GetLayerData(layer_index int32) RefImage
}

// TranslationVirtuals declares the Category-A virtual surface of Godot class Translation.
type TranslationVirtuals interface {
	V_Translation_GetPluralMessage(src_message StringName, src_plural_message StringName, n int32, context StringName) StringName
	V_Translation_GetMessage(src_message StringName, context StringName) StringName
}

// VisualInstance3DVirtuals declares the Category-A virtual surface of Godot class VisualInstance3D.
type VisualInstance3DVirtuals interface {
	V_VisualInstance3D_GetAabb() AABB
}

// VisualShaderNodeCustomVirtuals declares the Category-A virtual surface of Godot class VisualShaderNodeCustom.
type VisualShaderNodeCustomVirtuals interface {
	V_VisualShaderNodeCustom_GetName() String
	V_VisualShaderNodeCustom_GetInputPortDefaultValue(port int32) Variant
	V_VisualShaderNodeCustom_GetDefaultInputPort(typeName VisualShaderNodePortType) int32
}

// WebRTCDataChannelExtensionVirtuals declares the Category-A virtual surface of Godot class WebRTCDataChannelExtension.
type WebRTCDataChannelExtensionVirtuals interface {
	V_WebRTCDataChannelExtension_GetPacket(r_buffer **uint8, r_buffer_size *Int32T) Error
	V_WebRTCDataChannelExtension_PutPacket(buffer *uint8, buffer_size int32) Error
	V_WebRTCDataChannelExtension_GetAvailablePacketCount() int32
	V_WebRTCDataChannelExtension_Poll() Error
	V_WebRTCDataChannelExtension_GetWriteMode() WebRTCDataChannelWriteMode
	V_WebRTCDataChannelExtension_WasStringPacket() bool
	V_WebRTCDataChannelExtension_GetReadyState() WebRTCDataChannelChannelState
	V_WebRTCDataChannelExtension_GetLabel() String
	V_WebRTCDataChannelExtension_IsOrdered() bool
	V_WebRTCDataChannelExtension_GetId() int32
	V_WebRTCDataChannelExtension_GetMaxPacketLifeTime() int32
	V_WebRTCDataChannelExtension_GetMaxRetransmits() int32
	V_WebRTCDataChannelExtension_GetProtocol() String
	V_WebRTCDataChannelExtension_IsNegotiated() bool
	V_WebRTCDataChannelExtension_GetBufferedAmount() int32
}

// WebRTCPeerConnectionExtensionVirtuals declares the Category-A virtual surface of Godot class WebRTCPeerConnectionExtension.
type WebRTCPeerConnectionExtensionVirtuals interface {
	V_WebRTCPeerConnectionExtension_GetConnectionState() WebRTCPeerConnectionConnectionState
	V_WebRTCPeerConnectionExtension_GetGatheringState() WebRTCPeerConnectionGatheringState
	V_WebRTCPeerConnectionExtension_GetSignalingState() WebRTCPeerConnectionSignalingState
	V_WebRTCPeerConnectionExtension_Initialize(config Dictionary) Error
	V_WebRTCPeerConnectionExtension_CreateDataChannel(label String, config Dictionary) RefWebRTCDataChannel
	V_WebRTCPeerConnectionExtension_CreateOffer() Error
	V_WebRTCPeerConnectionExtension_SetRemoteDescription(typeName String, sdp String) Error
	V_WebRTCPeerConnectionExtension_SetLocalDescription(typeName String, sdp String) Error
	V_WebRTCPeerConnectionExtension_AddIceCandidate(sdp_mid_name String, sdp_mline_index int32, sdp_name String) Error
	V_WebRTCPeerConnectionExtension_Poll() Error
}

// WindowVirtuals declares the Category-A virtual surface of Godot class Window.
type WindowVirtuals interface {
	V_Window_GetContentsMinimumSize() Vector2
}

// XRInterfaceExtensionVirtuals declares the Category-A virtual surface of Godot class XRInterfaceExtension.
type XRInterfaceExtensionVirtuals interface {
	V_XRInterfaceExtension_GetName() StringName
	V_XRInterfaceExtension_GetCapabilities() uint32
	V_XRInterfaceExtension_IsInitialized() bool
	V_XRInterfaceExtension_Initialize() bool
	V_XRInterfaceExtension_GetSystemInfo() Dictionary
	V_XRInterfaceExtension_SupportsPlayAreaMode(mode XRInterfacePlayAreaMode) bool
	V_XRInterfaceExtension_GetPlayAreaMode() XRInterfacePlayAreaMode
	V_XRInterfaceExtension_SetPlayAreaMode(mode XRInterfacePlayAreaMode) bool
	V_XRInterfaceExtension_GetPlayArea() PackedVector3Array
	V_XRInterfaceExtension_GetRenderTargetSize() Vector2
	V_XRInterfaceExtension_GetViewCount() uint32
	V_XRInterfaceExtension_GetTransformForView(view uint32, cam_transform Transform3D) Transform3D
	V_XRInterfaceExtension_GetProjectionForView(view uint32, aspect float64, z_near float64, z_far float64) PackedFloat64Array
	V_XRInterfaceExtension_GetTrackingStatus() XRInterfaceTrackingStatus
	V_XRInterfaceExtension_GetAnchorDetectionIsEnabled() bool
	V_XRInterfaceExtension_GetCameraFeedId() int32
	V_XRInterfaceExtension_GetColorTexture() RID
	V_XRInterfaceExtension_GetDepthTexture() RID
	V_XRInterfaceExtension_GetVelocityTexture() RID
}
