package builtin

/*------------------------------------------------------------------------------
//   This code was generated by template classes.refs.go.tmpl.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "classes.refs.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/

//revive:disable

// refcount classes
type RefAESContext interface {
	Ref
	Ptr() AESContext
}
type RefAStar2D interface {
	Ref
	Ptr() AStar2D
}
type RefAStar3D interface {
	Ref
	Ptr() AStar3D
}
type RefAStarGrid2D interface {
	Ref
	Ptr() AStarGrid2D
}
type RefAnimatedTexture interface {
	Ref
	Ptr() AnimatedTexture
}
type RefAnimation interface {
	Ref
	Ptr() Animation
}
type RefAnimationLibrary interface {
	Ref
	Ptr() AnimationLibrary
}
type RefAnimationNode interface {
	Ref
	Ptr() AnimationNode
}
type RefAnimationNodeAdd2 interface {
	Ref
	Ptr() AnimationNodeAdd2
}
type RefAnimationNodeAdd3 interface {
	Ref
	Ptr() AnimationNodeAdd3
}
type RefAnimationNodeAnimation interface {
	Ref
	Ptr() AnimationNodeAnimation
}
type RefAnimationNodeBlend2 interface {
	Ref
	Ptr() AnimationNodeBlend2
}
type RefAnimationNodeBlend3 interface {
	Ref
	Ptr() AnimationNodeBlend3
}
type RefAnimationNodeBlendSpace1D interface {
	Ref
	Ptr() AnimationNodeBlendSpace1D
}
type RefAnimationNodeBlendSpace2D interface {
	Ref
	Ptr() AnimationNodeBlendSpace2D
}
type RefAnimationNodeBlendTree interface {
	Ref
	Ptr() AnimationNodeBlendTree
}
type RefAnimationNodeExtension interface {
	Ref
	Ptr() AnimationNodeExtension
}
type RefAnimationNodeOneShot interface {
	Ref
	Ptr() AnimationNodeOneShot
}
type RefAnimationNodeOutput interface {
	Ref
	Ptr() AnimationNodeOutput
}
type RefAnimationNodeStateMachine interface {
	Ref
	Ptr() AnimationNodeStateMachine
}
type RefAnimationNodeStateMachinePlayback interface {
	Ref
	Ptr() AnimationNodeStateMachinePlayback
}
type RefAnimationNodeStateMachineTransition interface {
	Ref
	Ptr() AnimationNodeStateMachineTransition
}
type RefAnimationNodeSub2 interface {
	Ref
	Ptr() AnimationNodeSub2
}
type RefAnimationNodeSync interface {
	Ref
	Ptr() AnimationNodeSync
}
type RefAnimationNodeTimeScale interface {
	Ref
	Ptr() AnimationNodeTimeScale
}
type RefAnimationNodeTimeSeek interface {
	Ref
	Ptr() AnimationNodeTimeSeek
}
type RefAnimationNodeTransition interface {
	Ref
	Ptr() AnimationNodeTransition
}
type RefAnimationRootNode interface {
	Ref
	Ptr() AnimationRootNode
}
type RefArrayMesh interface {
	Ref
	Ptr() ArrayMesh
}
type RefArrayOccluder3D interface {
	Ref
	Ptr() ArrayOccluder3D
}
type RefAtlasTexture interface {
	Ref
	Ptr() AtlasTexture
}
type RefAudioBusLayout interface {
	Ref
	Ptr() AudioBusLayout
}
type RefAudioEffect interface {
	Ref
	Ptr() AudioEffect
}
type RefAudioEffectAmplify interface {
	Ref
	Ptr() AudioEffectAmplify
}
type RefAudioEffectBandLimitFilter interface {
	Ref
	Ptr() AudioEffectBandLimitFilter
}
type RefAudioEffectBandPassFilter interface {
	Ref
	Ptr() AudioEffectBandPassFilter
}
type RefAudioEffectCapture interface {
	Ref
	Ptr() AudioEffectCapture
}
type RefAudioEffectChorus interface {
	Ref
	Ptr() AudioEffectChorus
}
type RefAudioEffectCompressor interface {
	Ref
	Ptr() AudioEffectCompressor
}
type RefAudioEffectDelay interface {
	Ref
	Ptr() AudioEffectDelay
}
type RefAudioEffectDistortion interface {
	Ref
	Ptr() AudioEffectDistortion
}
type RefAudioEffectEQ interface {
	Ref
	Ptr() AudioEffectEQ
}
type RefAudioEffectEQ10 interface {
	Ref
	Ptr() AudioEffectEQ10
}
type RefAudioEffectEQ21 interface {
	Ref
	Ptr() AudioEffectEQ21
}
type RefAudioEffectEQ6 interface {
	Ref
	Ptr() AudioEffectEQ6
}
type RefAudioEffectFilter interface {
	Ref
	Ptr() AudioEffectFilter
}
type RefAudioEffectHardLimiter interface {
	Ref
	Ptr() AudioEffectHardLimiter
}
type RefAudioEffectHighPassFilter interface {
	Ref
	Ptr() AudioEffectHighPassFilter
}
type RefAudioEffectHighShelfFilter interface {
	Ref
	Ptr() AudioEffectHighShelfFilter
}
type RefAudioEffectInstance interface {
	Ref
	Ptr() AudioEffectInstance
}
type RefAudioEffectLimiter interface {
	Ref
	Ptr() AudioEffectLimiter
}
type RefAudioEffectLowPassFilter interface {
	Ref
	Ptr() AudioEffectLowPassFilter
}
type RefAudioEffectLowShelfFilter interface {
	Ref
	Ptr() AudioEffectLowShelfFilter
}
type RefAudioEffectNotchFilter interface {
	Ref
	Ptr() AudioEffectNotchFilter
}
type RefAudioEffectPanner interface {
	Ref
	Ptr() AudioEffectPanner
}
type RefAudioEffectPhaser interface {
	Ref
	Ptr() AudioEffectPhaser
}
type RefAudioEffectPitchShift interface {
	Ref
	Ptr() AudioEffectPitchShift
}
type RefAudioEffectRecord interface {
	Ref
	Ptr() AudioEffectRecord
}
type RefAudioEffectReverb interface {
	Ref
	Ptr() AudioEffectReverb
}
type RefAudioEffectSpectrumAnalyzer interface {
	Ref
	Ptr() AudioEffectSpectrumAnalyzer
}
type RefAudioEffectSpectrumAnalyzerInstance interface {
	Ref
	Ptr() AudioEffectSpectrumAnalyzerInstance
}
type RefAudioEffectStereoEnhance interface {
	Ref
	Ptr() AudioEffectStereoEnhance
}
type RefAudioSample interface {
	Ref
	Ptr() AudioSample
}
type RefAudioSamplePlayback interface {
	Ref
	Ptr() AudioSamplePlayback
}
type RefAudioStream interface {
	Ref
	Ptr() AudioStream
}
type RefAudioStreamGenerator interface {
	Ref
	Ptr() AudioStreamGenerator
}
type RefAudioStreamGeneratorPlayback interface {
	Ref
	Ptr() AudioStreamGeneratorPlayback
}
type RefAudioStreamInteractive interface {
	Ref
	Ptr() AudioStreamInteractive
}
type RefAudioStreamMP3 interface {
	Ref
	Ptr() AudioStreamMP3
}
type RefAudioStreamMicrophone interface {
	Ref
	Ptr() AudioStreamMicrophone
}
type RefAudioStreamOggVorbis interface {
	Ref
	Ptr() AudioStreamOggVorbis
}
type RefAudioStreamPlayback interface {
	Ref
	Ptr() AudioStreamPlayback
}
type RefAudioStreamPlaybackInteractive interface {
	Ref
	Ptr() AudioStreamPlaybackInteractive
}
type RefAudioStreamPlaybackOggVorbis interface {
	Ref
	Ptr() AudioStreamPlaybackOggVorbis
}
type RefAudioStreamPlaybackPlaylist interface {
	Ref
	Ptr() AudioStreamPlaybackPlaylist
}
type RefAudioStreamPlaybackPolyphonic interface {
	Ref
	Ptr() AudioStreamPlaybackPolyphonic
}
type RefAudioStreamPlaybackResampled interface {
	Ref
	Ptr() AudioStreamPlaybackResampled
}
type RefAudioStreamPlaybackSynchronized interface {
	Ref
	Ptr() AudioStreamPlaybackSynchronized
}
type RefAudioStreamPlaylist interface {
	Ref
	Ptr() AudioStreamPlaylist
}
type RefAudioStreamPolyphonic interface {
	Ref
	Ptr() AudioStreamPolyphonic
}
type RefAudioStreamRandomizer interface {
	Ref
	Ptr() AudioStreamRandomizer
}
type RefAudioStreamSynchronized interface {
	Ref
	Ptr() AudioStreamSynchronized
}
type RefAudioStreamWAV interface {
	Ref
	Ptr() AudioStreamWAV
}
type RefAwaitTweener interface {
	Ref
	Ptr() AwaitTweener
}
type RefBaseMaterial3D interface {
	Ref
	Ptr() BaseMaterial3D
}
type RefBitMap interface {
	Ref
	Ptr() BitMap
}
type RefBlitMaterial interface {
	Ref
	Ptr() BlitMaterial
}
type RefBoneMap interface {
	Ref
	Ptr() BoneMap
}
type RefBoxMesh interface {
	Ref
	Ptr() BoxMesh
}
type RefBoxOccluder3D interface {
	Ref
	Ptr() BoxOccluder3D
}
type RefBoxShape3D interface {
	Ref
	Ptr() BoxShape3D
}
type RefButtonGroup interface {
	Ref
	Ptr() ButtonGroup
}
type RefCallbackTweener interface {
	Ref
	Ptr() CallbackTweener
}
type RefCameraAttributes interface {
	Ref
	Ptr() CameraAttributes
}
type RefCameraAttributesPhysical interface {
	Ref
	Ptr() CameraAttributesPhysical
}
type RefCameraAttributesPractical interface {
	Ref
	Ptr() CameraAttributesPractical
}
type RefCameraFeed interface {
	Ref
	Ptr() CameraFeed
}
type RefCameraTexture interface {
	Ref
	Ptr() CameraTexture
}
type RefCanvasItemMaterial interface {
	Ref
	Ptr() CanvasItemMaterial
}
type RefCanvasTexture interface {
	Ref
	Ptr() CanvasTexture
}
type RefCapsuleMesh interface {
	Ref
	Ptr() CapsuleMesh
}
type RefCapsuleShape2D interface {
	Ref
	Ptr() CapsuleShape2D
}
type RefCapsuleShape3D interface {
	Ref
	Ptr() CapsuleShape3D
}
type RefCharFXTransform interface {
	Ref
	Ptr() CharFXTransform
}
type RefCircleShape2D interface {
	Ref
	Ptr() CircleShape2D
}
type RefCodeHighlighter interface {
	Ref
	Ptr() CodeHighlighter
}
type RefColorPalette interface {
	Ref
	Ptr() ColorPalette
}
type RefCompositor interface {
	Ref
	Ptr() Compositor
}
type RefCompositorEffect interface {
	Ref
	Ptr() CompositorEffect
}
type RefCompressedCubemap interface {
	Ref
	Ptr() CompressedCubemap
}
type RefCompressedCubemapArray interface {
	Ref
	Ptr() CompressedCubemapArray
}
type RefCompressedTexture2D interface {
	Ref
	Ptr() CompressedTexture2D
}
type RefCompressedTexture2DArray interface {
	Ref
	Ptr() CompressedTexture2DArray
}
type RefCompressedTexture3D interface {
	Ref
	Ptr() CompressedTexture3D
}
type RefCompressedTextureLayered interface {
	Ref
	Ptr() CompressedTextureLayered
}
type RefConcavePolygonShape2D interface {
	Ref
	Ptr() ConcavePolygonShape2D
}
type RefConcavePolygonShape3D interface {
	Ref
	Ptr() ConcavePolygonShape3D
}
type RefConfigFile interface {
	Ref
	Ptr() ConfigFile
}
type RefConvexPolygonShape2D interface {
	Ref
	Ptr() ConvexPolygonShape2D
}
type RefConvexPolygonShape3D interface {
	Ref
	Ptr() ConvexPolygonShape3D
}
type RefCrypto interface {
	Ref
	Ptr() Crypto
}
type RefCryptoKey interface {
	Ref
	Ptr() CryptoKey
}
type RefCubemap interface {
	Ref
	Ptr() Cubemap
}
type RefCubemapArray interface {
	Ref
	Ptr() CubemapArray
}
type RefCurve interface {
	Ref
	Ptr() Curve
}
type RefCurve2D interface {
	Ref
	Ptr() Curve2D
}
type RefCurve3D interface {
	Ref
	Ptr() Curve3D
}
type RefCurveTexture interface {
	Ref
	Ptr() CurveTexture
}
type RefCurveXYZTexture interface {
	Ref
	Ptr() CurveXYZTexture
}
type RefCylinderMesh interface {
	Ref
	Ptr() CylinderMesh
}
type RefCylinderShape3D interface {
	Ref
	Ptr() CylinderShape3D
}
type RefDPITexture interface {
	Ref
	Ptr() DPITexture
}
type RefDTLSServer interface {
	Ref
	Ptr() DTLSServer
}
type RefDirAccess interface {
	Ref
	Ptr() DirAccess
}
type RefDrawableTexture2D interface {
	Ref
	Ptr() DrawableTexture2D
}
type RefENetConnection interface {
	Ref
	Ptr() ENetConnection
}
type RefENetMultiplayerPeer interface {
	Ref
	Ptr() ENetMultiplayerPeer
}
type RefENetPacketPeer interface {
	Ref
	Ptr() ENetPacketPeer
}
type RefEditorContextMenuPlugin interface {
	Ref
	Ptr() EditorContextMenuPlugin
}
type RefEditorDebuggerPlugin interface {
	Ref
	Ptr() EditorDebuggerPlugin
}
type RefEditorDebuggerSession interface {
	Ref
	Ptr() EditorDebuggerSession
}
type RefEditorExportPlatform interface {
	Ref
	Ptr() EditorExportPlatform
}
type RefEditorExportPlatformAndroid interface {
	Ref
	Ptr() EditorExportPlatformAndroid
}
type RefEditorExportPlatformAppleEmbedded interface {
	Ref
	Ptr() EditorExportPlatformAppleEmbedded
}
type RefEditorExportPlatformExtension interface {
	Ref
	Ptr() EditorExportPlatformExtension
}
type RefEditorExportPlatformIOS interface {
	Ref
	Ptr() EditorExportPlatformIOS
}
type RefEditorExportPlatformLinuxBSD interface {
	Ref
	Ptr() EditorExportPlatformLinuxBSD
}
type RefEditorExportPlatformMacOS interface {
	Ref
	Ptr() EditorExportPlatformMacOS
}
type RefEditorExportPlatformPC interface {
	Ref
	Ptr() EditorExportPlatformPC
}
type RefEditorExportPlatformVisionOS interface {
	Ref
	Ptr() EditorExportPlatformVisionOS
}
type RefEditorExportPlatformWeb interface {
	Ref
	Ptr() EditorExportPlatformWeb
}
type RefEditorExportPlatformWindows interface {
	Ref
	Ptr() EditorExportPlatformWindows
}
type RefEditorExportPlugin interface {
	Ref
	Ptr() EditorExportPlugin
}
type RefEditorExportPreset interface {
	Ref
	Ptr() EditorExportPreset
}
type RefEditorFeatureProfile interface {
	Ref
	Ptr() EditorFeatureProfile
}
type RefEditorFileSystemImportFormatSupportQuery interface {
	Ref
	Ptr() EditorFileSystemImportFormatSupportQuery
}
type RefEditorImportPlugin interface {
	Ref
	Ptr() EditorImportPlugin
}
type RefEditorInspectorPlugin interface {
	Ref
	Ptr() EditorInspectorPlugin
}
type RefEditorNode3DGizmo interface {
	Ref
	Ptr() EditorNode3DGizmo
}
type RefEditorNode3DGizmoPlugin interface {
	Ref
	Ptr() EditorNode3DGizmoPlugin
}
type RefEditorResourceConversionPlugin interface {
	Ref
	Ptr() EditorResourceConversionPlugin
}
type RefEditorResourcePreviewGenerator interface {
	Ref
	Ptr() EditorResourcePreviewGenerator
}
type RefEditorResourceTooltipPlugin interface {
	Ref
	Ptr() EditorResourceTooltipPlugin
}
type RefEditorSceneFormatImporter interface {
	Ref
	Ptr() EditorSceneFormatImporter
}
type RefEditorSceneFormatImporterBlend interface {
	Ref
	Ptr() EditorSceneFormatImporterBlend
}
type RefEditorSceneFormatImporterFBX2GLTF interface {
	Ref
	Ptr() EditorSceneFormatImporterFBX2GLTF
}
type RefEditorSceneFormatImporterGLTF interface {
	Ref
	Ptr() EditorSceneFormatImporterGLTF
}
type RefEditorSceneFormatImporterUFBX interface {
	Ref
	Ptr() EditorSceneFormatImporterUFBX
}
type RefEditorScenePostImport interface {
	Ref
	Ptr() EditorScenePostImport
}
type RefEditorScenePostImportPlugin interface {
	Ref
	Ptr() EditorScenePostImportPlugin
}
type RefEditorScript interface {
	Ref
	Ptr() EditorScript
}
type RefEditorSettings interface {
	Ref
	Ptr() EditorSettings
}
type RefEditorSyntaxHighlighter interface {
	Ref
	Ptr() EditorSyntaxHighlighter
}
type RefEditorTranslationParserPlugin interface {
	Ref
	Ptr() EditorTranslationParserPlugin
}
type RefEncodedObjectAsID interface {
	Ref
	Ptr() EncodedObjectAsID
}
type RefEngineProfiler interface {
	Ref
	Ptr() EngineProfiler
}
type RefEnvironment interface {
	Ref
	Ptr() Environment
}
type RefExpression interface {
	Ref
	Ptr() Expression
}
type RefExternalTexture interface {
	Ref
	Ptr() ExternalTexture
}
type RefFBXDocument interface {
	Ref
	Ptr() FBXDocument
}
type RefFBXState interface {
	Ref
	Ptr() FBXState
}
type RefFastNoiseLite interface {
	Ref
	Ptr() FastNoiseLite
}
type RefFileAccess interface {
	Ref
	Ptr() FileAccess
}
type RefFogMaterial interface {
	Ref
	Ptr() FogMaterial
}
type RefFoldableGroup interface {
	Ref
	Ptr() FoldableGroup
}
type RefFont interface {
	Ref
	Ptr() Font
}
type RefFontFile interface {
	Ref
	Ptr() FontFile
}
type RefFontVariation interface {
	Ref
	Ptr() FontVariation
}
type RefGDExtension interface {
	Ref
	Ptr() GDExtension
}
type RefGDScript interface {
	Ref
	Ptr() GDScript
}
type RefGDScriptSyntaxHighlighter interface {
	Ref
	Ptr() GDScriptSyntaxHighlighter
}
type RefGDScriptTextDocument interface {
	Ref
	Ptr() GDScriptTextDocument
}
type RefGDScriptWorkspace interface {
	Ref
	Ptr() GDScriptWorkspace
}
type RefGLTFAccessor interface {
	Ref
	Ptr() GLTFAccessor
}
type RefGLTFAnimation interface {
	Ref
	Ptr() GLTFAnimation
}
type RefGLTFBufferView interface {
	Ref
	Ptr() GLTFBufferView
}
type RefGLTFCamera interface {
	Ref
	Ptr() GLTFCamera
}
type RefGLTFDocument interface {
	Ref
	Ptr() GLTFDocument
}
type RefGLTFDocumentExtension interface {
	Ref
	Ptr() GLTFDocumentExtension
}
type RefGLTFDocumentExtensionConvertImporterMesh interface {
	Ref
	Ptr() GLTFDocumentExtensionConvertImporterMesh
}
type RefGLTFLight interface {
	Ref
	Ptr() GLTFLight
}
type RefGLTFMesh interface {
	Ref
	Ptr() GLTFMesh
}
type RefGLTFNode interface {
	Ref
	Ptr() GLTFNode
}
type RefGLTFObjectModelProperty interface {
	Ref
	Ptr() GLTFObjectModelProperty
}
type RefGLTFPhysicsBody interface {
	Ref
	Ptr() GLTFPhysicsBody
}
type RefGLTFPhysicsShape interface {
	Ref
	Ptr() GLTFPhysicsShape
}
type RefGLTFSkeleton interface {
	Ref
	Ptr() GLTFSkeleton
}
type RefGLTFSkin interface {
	Ref
	Ptr() GLTFSkin
}
type RefGLTFSpecGloss interface {
	Ref
	Ptr() GLTFSpecGloss
}
type RefGLTFState interface {
	Ref
	Ptr() GLTFState
}
type RefGLTFTexture interface {
	Ref
	Ptr() GLTFTexture
}
type RefGLTFTextureSampler interface {
	Ref
	Ptr() GLTFTextureSampler
}
type RefGradient interface {
	Ref
	Ptr() Gradient
}
type RefGradientTexture1D interface {
	Ref
	Ptr() GradientTexture1D
}
type RefGradientTexture2D interface {
	Ref
	Ptr() GradientTexture2D
}
type RefHMACContext interface {
	Ref
	Ptr() HMACContext
}
type RefHTTPClient interface {
	Ref
	Ptr() HTTPClient
}
type RefHashingContext interface {
	Ref
	Ptr() HashingContext
}
type RefHeightMapShape3D interface {
	Ref
	Ptr() HeightMapShape3D
}
type RefImage interface {
	Ref
	Ptr() Image
}
type RefImageFormatLoader interface {
	Ref
	Ptr() ImageFormatLoader
}
type RefImageFormatLoaderExtension interface {
	Ref
	Ptr() ImageFormatLoaderExtension
}
type RefImageTexture interface {
	Ref
	Ptr() ImageTexture
}
type RefImageTexture3D interface {
	Ref
	Ptr() ImageTexture3D
}
type RefImageTextureLayered interface {
	Ref
	Ptr() ImageTextureLayered
}
type RefImmediateMesh interface {
	Ref
	Ptr() ImmediateMesh
}
type RefImporterMesh interface {
	Ref
	Ptr() ImporterMesh
}
type RefInputEvent interface {
	Ref
	Ptr() InputEvent
}
type RefInputEventAction interface {
	Ref
	Ptr() InputEventAction
}
type RefInputEventFromWindow interface {
	Ref
	Ptr() InputEventFromWindow
}
type RefInputEventGesture interface {
	Ref
	Ptr() InputEventGesture
}
type RefInputEventJoypadButton interface {
	Ref
	Ptr() InputEventJoypadButton
}
type RefInputEventJoypadMotion interface {
	Ref
	Ptr() InputEventJoypadMotion
}
type RefInputEventKey interface {
	Ref
	Ptr() InputEventKey
}
type RefInputEventMIDI interface {
	Ref
	Ptr() InputEventMIDI
}
type RefInputEventMagnifyGesture interface {
	Ref
	Ptr() InputEventMagnifyGesture
}
type RefInputEventMouse interface {
	Ref
	Ptr() InputEventMouse
}
type RefInputEventMouseButton interface {
	Ref
	Ptr() InputEventMouseButton
}
type RefInputEventMouseMotion interface {
	Ref
	Ptr() InputEventMouseMotion
}
type RefInputEventPanGesture interface {
	Ref
	Ptr() InputEventPanGesture
}
type RefInputEventScreenDrag interface {
	Ref
	Ptr() InputEventScreenDrag
}
type RefInputEventScreenTouch interface {
	Ref
	Ptr() InputEventScreenTouch
}
type RefInputEventShortcut interface {
	Ref
	Ptr() InputEventShortcut
}
type RefInputEventWithModifiers interface {
	Ref
	Ptr() InputEventWithModifiers
}
type RefIntervalTweener interface {
	Ref
	Ptr() IntervalTweener
}
type RefJSON interface {
	Ref
	Ptr() JSON
}
type RefJavaClass interface {
	Ref
	Ptr() JavaClass
}
type RefJavaObject interface {
	Ref
	Ptr() JavaObject
}
type RefJavaScriptObject interface {
	Ref
	Ptr() JavaScriptObject
}
type RefJointLimitation3D interface {
	Ref
	Ptr() JointLimitation3D
}
type RefJointLimitationCone3D interface {
	Ref
	Ptr() JointLimitationCone3D
}
type RefKinematicCollision2D interface {
	Ref
	Ptr() KinematicCollision2D
}
type RefKinematicCollision3D interface {
	Ref
	Ptr() KinematicCollision3D
}
type RefLabelSettings interface {
	Ref
	Ptr() LabelSettings
}
type RefLightmapGIData interface {
	Ref
	Ptr() LightmapGIData
}
type RefLightmapper interface {
	Ref
	Ptr() Lightmapper
}
type RefLightmapperRD interface {
	Ref
	Ptr() LightmapperRD
}
type RefLogger interface {
	Ref
	Ptr() Logger
}
type RefMaterial interface {
	Ref
	Ptr() Material
}
type RefMesh interface {
	Ref
	Ptr() Mesh
}
type RefMeshConvexDecompositionSettings interface {
	Ref
	Ptr() MeshConvexDecompositionSettings
}
type RefMeshDataTool interface {
	Ref
	Ptr() MeshDataTool
}
type RefMeshLibrary interface {
	Ref
	Ptr() MeshLibrary
}
type RefMeshTexture interface {
	Ref
	Ptr() MeshTexture
}
type RefMethodTweener interface {
	Ref
	Ptr() MethodTweener
}
type RefMissingResource interface {
	Ref
	Ptr() MissingResource
}
type RefMobileVRInterface interface {
	Ref
	Ptr() MobileVRInterface
}
type RefMultiMesh interface {
	Ref
	Ptr() MultiMesh
}
type RefMultiplayerAPI interface {
	Ref
	Ptr() MultiplayerAPI
}
type RefMultiplayerAPIExtension interface {
	Ref
	Ptr() MultiplayerAPIExtension
}
type RefMultiplayerPeer interface {
	Ref
	Ptr() MultiplayerPeer
}
type RefMultiplayerPeerExtension interface {
	Ref
	Ptr() MultiplayerPeerExtension
}
type RefMutex interface {
	Ref
	Ptr() Mutex
}
type RefNavigationMesh interface {
	Ref
	Ptr() NavigationMesh
}
type RefNavigationMeshSourceGeometryData2D interface {
	Ref
	Ptr() NavigationMeshSourceGeometryData2D
}
type RefNavigationMeshSourceGeometryData3D interface {
	Ref
	Ptr() NavigationMeshSourceGeometryData3D
}
type RefNavigationPathQueryParameters2D interface {
	Ref
	Ptr() NavigationPathQueryParameters2D
}
type RefNavigationPathQueryParameters3D interface {
	Ref
	Ptr() NavigationPathQueryParameters3D
}
type RefNavigationPathQueryResult2D interface {
	Ref
	Ptr() NavigationPathQueryResult2D
}
type RefNavigationPathQueryResult3D interface {
	Ref
	Ptr() NavigationPathQueryResult3D
}
type RefNavigationPolygon interface {
	Ref
	Ptr() NavigationPolygon
}
type RefNode3DGizmo interface {
	Ref
	Ptr() Node3DGizmo
}
type RefNoise interface {
	Ref
	Ptr() Noise
}
type RefNoiseTexture2D interface {
	Ref
	Ptr() NoiseTexture2D
}
type RefNoiseTexture3D interface {
	Ref
	Ptr() NoiseTexture3D
}
type RefORMMaterial3D interface {
	Ref
	Ptr() ORMMaterial3D
}
type RefOccluder3D interface {
	Ref
	Ptr() Occluder3D
}
type RefOccluderPolygon2D interface {
	Ref
	Ptr() OccluderPolygon2D
}
type RefOfflineMultiplayerPeer interface {
	Ref
	Ptr() OfflineMultiplayerPeer
}
type RefOggPacketSequence interface {
	Ref
	Ptr() OggPacketSequence
}
type RefOggPacketSequencePlayback interface {
	Ref
	Ptr() OggPacketSequencePlayback
}
type RefOpenXRAPIExtension interface {
	Ref
	Ptr() OpenXRAPIExtension
}
type RefOpenXRAction interface {
	Ref
	Ptr() OpenXRAction
}
type RefOpenXRActionBindingModifier interface {
	Ref
	Ptr() OpenXRActionBindingModifier
}
type RefOpenXRActionMap interface {
	Ref
	Ptr() OpenXRActionMap
}
type RefOpenXRActionSet interface {
	Ref
	Ptr() OpenXRActionSet
}
type RefOpenXRAnalogThresholdModifier interface {
	Ref
	Ptr() OpenXRAnalogThresholdModifier
}
type RefOpenXRAnchorTracker interface {
	Ref
	Ptr() OpenXRAnchorTracker
}
type RefOpenXRBindingModifier interface {
	Ref
	Ptr() OpenXRBindingModifier
}
type RefOpenXRDpadBindingModifier interface {
	Ref
	Ptr() OpenXRDpadBindingModifier
}
type RefOpenXRFutureResult interface {
	Ref
	Ptr() OpenXRFutureResult
}
type RefOpenXRHapticBase interface {
	Ref
	Ptr() OpenXRHapticBase
}
type RefOpenXRHapticVibration interface {
	Ref
	Ptr() OpenXRHapticVibration
}
type RefOpenXRIPBinding interface {
	Ref
	Ptr() OpenXRIPBinding
}
type RefOpenXRIPBindingModifier interface {
	Ref
	Ptr() OpenXRIPBindingModifier
}
type RefOpenXRInteractionProfile interface {
	Ref
	Ptr() OpenXRInteractionProfile
}
type RefOpenXRInterface interface {
	Ref
	Ptr() OpenXRInterface
}
type RefOpenXRMarkerTracker interface {
	Ref
	Ptr() OpenXRMarkerTracker
}
type RefOpenXRPlaneTracker interface {
	Ref
	Ptr() OpenXRPlaneTracker
}
type RefOpenXRSpatialCapabilityConfigurationAnchor interface {
	Ref
	Ptr() OpenXRSpatialCapabilityConfigurationAnchor
}
type RefOpenXRSpatialCapabilityConfigurationAprilTag interface {
	Ref
	Ptr() OpenXRSpatialCapabilityConfigurationAprilTag
}
type RefOpenXRSpatialCapabilityConfigurationAruco interface {
	Ref
	Ptr() OpenXRSpatialCapabilityConfigurationAruco
}
type RefOpenXRSpatialCapabilityConfigurationBaseHeader interface {
	Ref
	Ptr() OpenXRSpatialCapabilityConfigurationBaseHeader
}
type RefOpenXRSpatialCapabilityConfigurationMicroQrCode interface {
	Ref
	Ptr() OpenXRSpatialCapabilityConfigurationMicroQrCode
}
type RefOpenXRSpatialCapabilityConfigurationPlaneTracking interface {
	Ref
	Ptr() OpenXRSpatialCapabilityConfigurationPlaneTracking
}
type RefOpenXRSpatialCapabilityConfigurationQrCode interface {
	Ref
	Ptr() OpenXRSpatialCapabilityConfigurationQrCode
}
type RefOpenXRSpatialComponentAnchorList interface {
	Ref
	Ptr() OpenXRSpatialComponentAnchorList
}
type RefOpenXRSpatialComponentBounded2DList interface {
	Ref
	Ptr() OpenXRSpatialComponentBounded2DList
}
type RefOpenXRSpatialComponentBounded3DList interface {
	Ref
	Ptr() OpenXRSpatialComponentBounded3DList
}
type RefOpenXRSpatialComponentData interface {
	Ref
	Ptr() OpenXRSpatialComponentData
}
type RefOpenXRSpatialComponentMarkerList interface {
	Ref
	Ptr() OpenXRSpatialComponentMarkerList
}
type RefOpenXRSpatialComponentMesh2DList interface {
	Ref
	Ptr() OpenXRSpatialComponentMesh2DList
}
type RefOpenXRSpatialComponentMesh3DList interface {
	Ref
	Ptr() OpenXRSpatialComponentMesh3DList
}
type RefOpenXRSpatialComponentParentList interface {
	Ref
	Ptr() OpenXRSpatialComponentParentList
}
type RefOpenXRSpatialComponentPersistenceList interface {
	Ref
	Ptr() OpenXRSpatialComponentPersistenceList
}
type RefOpenXRSpatialComponentPlaneAlignmentList interface {
	Ref
	Ptr() OpenXRSpatialComponentPlaneAlignmentList
}
type RefOpenXRSpatialComponentPlaneSemanticLabelList interface {
	Ref
	Ptr() OpenXRSpatialComponentPlaneSemanticLabelList
}
type RefOpenXRSpatialComponentPolygon2DList interface {
	Ref
	Ptr() OpenXRSpatialComponentPolygon2DList
}
type RefOpenXRSpatialContextPersistenceConfig interface {
	Ref
	Ptr() OpenXRSpatialContextPersistenceConfig
}
type RefOpenXRSpatialEntityTracker interface {
	Ref
	Ptr() OpenXRSpatialEntityTracker
}
type RefOpenXRSpatialQueryResultData interface {
	Ref
	Ptr() OpenXRSpatialQueryResultData
}
type RefOpenXRStructureBase interface {
	Ref
	Ptr() OpenXRStructureBase
}
type RefOptimizedTranslation interface {
	Ref
	Ptr() OptimizedTranslation
}
type RefPCKPacker interface {
	Ref
	Ptr() PCKPacker
}
type RefPackedDataContainer interface {
	Ref
	Ptr() PackedDataContainer
}
type RefPackedDataContainerRef interface {
	Ref
	Ptr() PackedDataContainerRef
}
type RefPackedScene interface {
	Ref
	Ptr() PackedScene
}
type RefPacketPeer interface {
	Ref
	Ptr() PacketPeer
}
type RefPacketPeerDTLS interface {
	Ref
	Ptr() PacketPeerDTLS
}
type RefPacketPeerExtension interface {
	Ref
	Ptr() PacketPeerExtension
}
type RefPacketPeerStream interface {
	Ref
	Ptr() PacketPeerStream
}
type RefPacketPeerUDP interface {
	Ref
	Ptr() PacketPeerUDP
}
type RefPanoramaSkyMaterial interface {
	Ref
	Ptr() PanoramaSkyMaterial
}
type RefParticleProcessMaterial interface {
	Ref
	Ptr() ParticleProcessMaterial
}
type RefPhysicalSkyMaterial interface {
	Ref
	Ptr() PhysicalSkyMaterial
}
type RefPhysicsMaterial interface {
	Ref
	Ptr() PhysicsMaterial
}
type RefPhysicsPointQueryParameters2D interface {
	Ref
	Ptr() PhysicsPointQueryParameters2D
}
type RefPhysicsPointQueryParameters3D interface {
	Ref
	Ptr() PhysicsPointQueryParameters3D
}
type RefPhysicsRayQueryParameters2D interface {
	Ref
	Ptr() PhysicsRayQueryParameters2D
}
type RefPhysicsRayQueryParameters3D interface {
	Ref
	Ptr() PhysicsRayQueryParameters3D
}
type RefPhysicsShapeQueryParameters2D interface {
	Ref
	Ptr() PhysicsShapeQueryParameters2D
}
type RefPhysicsShapeQueryParameters3D interface {
	Ref
	Ptr() PhysicsShapeQueryParameters3D
}
type RefPhysicsTestMotionParameters2D interface {
	Ref
	Ptr() PhysicsTestMotionParameters2D
}
type RefPhysicsTestMotionParameters3D interface {
	Ref
	Ptr() PhysicsTestMotionParameters3D
}
type RefPhysicsTestMotionResult2D interface {
	Ref
	Ptr() PhysicsTestMotionResult2D
}
type RefPhysicsTestMotionResult3D interface {
	Ref
	Ptr() PhysicsTestMotionResult3D
}
type RefPlaceholderCubemap interface {
	Ref
	Ptr() PlaceholderCubemap
}
type RefPlaceholderCubemapArray interface {
	Ref
	Ptr() PlaceholderCubemapArray
}
type RefPlaceholderMaterial interface {
	Ref
	Ptr() PlaceholderMaterial
}
type RefPlaceholderMesh interface {
	Ref
	Ptr() PlaceholderMesh
}
type RefPlaceholderTexture2D interface {
	Ref
	Ptr() PlaceholderTexture2D
}
type RefPlaceholderTexture2DArray interface {
	Ref
	Ptr() PlaceholderTexture2DArray
}
type RefPlaceholderTexture3D interface {
	Ref
	Ptr() PlaceholderTexture3D
}
type RefPlaceholderTextureLayered interface {
	Ref
	Ptr() PlaceholderTextureLayered
}
type RefPlaneMesh interface {
	Ref
	Ptr() PlaneMesh
}
type RefPointMesh interface {
	Ref
	Ptr() PointMesh
}
type RefPolygonOccluder3D interface {
	Ref
	Ptr() PolygonOccluder3D
}
type RefPolygonPathFinder interface {
	Ref
	Ptr() PolygonPathFinder
}
type RefPortableCompressedTexture2D interface {
	Ref
	Ptr() PortableCompressedTexture2D
}
type RefPrimitiveMesh interface {
	Ref
	Ptr() PrimitiveMesh
}
type RefPrismMesh interface {
	Ref
	Ptr() PrismMesh
}
type RefProceduralSkyMaterial interface {
	Ref
	Ptr() ProceduralSkyMaterial
}
type RefPropertyTweener interface {
	Ref
	Ptr() PropertyTweener
}
type RefQuadMesh interface {
	Ref
	Ptr() QuadMesh
}
type RefQuadOccluder3D interface {
	Ref
	Ptr() QuadOccluder3D
}
type RefRDAccelerationStructureGeometry interface {
	Ref
	Ptr() RDAccelerationStructureGeometry
}
type RefRDAccelerationStructureInstance interface {
	Ref
	Ptr() RDAccelerationStructureInstance
}
type RefRDAttachmentFormat interface {
	Ref
	Ptr() RDAttachmentFormat
}
type RefRDFramebufferPass interface {
	Ref
	Ptr() RDFramebufferPass
}
type RefRDHitGroup interface {
	Ref
	Ptr() RDHitGroup
}
type RefRDPipelineColorBlendState interface {
	Ref
	Ptr() RDPipelineColorBlendState
}
type RefRDPipelineColorBlendStateAttachment interface {
	Ref
	Ptr() RDPipelineColorBlendStateAttachment
}
type RefRDPipelineDepthStencilState interface {
	Ref
	Ptr() RDPipelineDepthStencilState
}
type RefRDPipelineMultisampleState interface {
	Ref
	Ptr() RDPipelineMultisampleState
}
type RefRDPipelineRasterizationState interface {
	Ref
	Ptr() RDPipelineRasterizationState
}
type RefRDPipelineShader interface {
	Ref
	Ptr() RDPipelineShader
}
type RefRDPipelineSpecializationConstant interface {
	Ref
	Ptr() RDPipelineSpecializationConstant
}
type RefRDSamplerState interface {
	Ref
	Ptr() RDSamplerState
}
type RefRDShaderFile interface {
	Ref
	Ptr() RDShaderFile
}
type RefRDShaderSPIRV interface {
	Ref
	Ptr() RDShaderSPIRV
}
type RefRDShaderSource interface {
	Ref
	Ptr() RDShaderSource
}
type RefRDTextureFormat interface {
	Ref
	Ptr() RDTextureFormat
}
type RefRDTextureView interface {
	Ref
	Ptr() RDTextureView
}
type RefRDUniform interface {
	Ref
	Ptr() RDUniform
}
type RefRDVertexAttribute interface {
	Ref
	Ptr() RDVertexAttribute
}
type RefRandomNumberGenerator interface {
	Ref
	Ptr() RandomNumberGenerator
}
type RefRectangleShape2D interface {
	Ref
	Ptr() RectangleShape2D
}
type RefRefCounted interface {
	Ref
	Ptr() RefCounted
}
type RefRegEx interface {
	Ref
	Ptr() RegEx
}
type RefRegExMatch interface {
	Ref
	Ptr() RegExMatch
}
type RefRenderSceneBuffers interface {
	Ref
	Ptr() RenderSceneBuffers
}
type RefRenderSceneBuffersConfiguration interface {
	Ref
	Ptr() RenderSceneBuffersConfiguration
}
type RefRenderSceneBuffersExtension interface {
	Ref
	Ptr() RenderSceneBuffersExtension
}
type RefRenderSceneBuffersRD interface {
	Ref
	Ptr() RenderSceneBuffersRD
}
type RefResource interface {
	Ref
	Ptr() Resource
}
type RefResourceFormatLoader interface {
	Ref
	Ptr() ResourceFormatLoader
}
type RefResourceFormatSaver interface {
	Ref
	Ptr() ResourceFormatSaver
}
type RefResourceImporter interface {
	Ref
	Ptr() ResourceImporter
}
type RefResourceImporterBMFont interface {
	Ref
	Ptr() ResourceImporterBMFont
}
type RefResourceImporterBitMap interface {
	Ref
	Ptr() ResourceImporterBitMap
}
type RefResourceImporterCSVTranslation interface {
	Ref
	Ptr() ResourceImporterCSVTranslation
}
type RefResourceImporterDynamicFont interface {
	Ref
	Ptr() ResourceImporterDynamicFont
}
type RefResourceImporterImage interface {
	Ref
	Ptr() ResourceImporterImage
}
type RefResourceImporterImageFont interface {
	Ref
	Ptr() ResourceImporterImageFont
}
type RefResourceImporterLayeredTexture interface {
	Ref
	Ptr() ResourceImporterLayeredTexture
}
type RefResourceImporterMP3 interface {
	Ref
	Ptr() ResourceImporterMP3
}
type RefResourceImporterOBJ interface {
	Ref
	Ptr() ResourceImporterOBJ
}
type RefResourceImporterOggVorbis interface {
	Ref
	Ptr() ResourceImporterOggVorbis
}
type RefResourceImporterSVG interface {
	Ref
	Ptr() ResourceImporterSVG
}
type RefResourceImporterScene interface {
	Ref
	Ptr() ResourceImporterScene
}
type RefResourceImporterShaderFile interface {
	Ref
	Ptr() ResourceImporterShaderFile
}
type RefResourceImporterTexture interface {
	Ref
	Ptr() ResourceImporterTexture
}
type RefResourceImporterTextureAtlas interface {
	Ref
	Ptr() ResourceImporterTextureAtlas
}
type RefResourceImporterWAV interface {
	Ref
	Ptr() ResourceImporterWAV
}
type RefRibbonTrailMesh interface {
	Ref
	Ptr() RibbonTrailMesh
}
type RefRichTextEffect interface {
	Ref
	Ptr() RichTextEffect
}
type RefSceneMultiplayer interface {
	Ref
	Ptr() SceneMultiplayer
}
type RefSceneReplicationConfig interface {
	Ref
	Ptr() SceneReplicationConfig
}
type RefSceneState interface {
	Ref
	Ptr() SceneState
}
type RefSceneTreeTimer interface {
	Ref
	Ptr() SceneTreeTimer
}
type RefScript interface {
	Ref
	Ptr() Script
}
type RefScriptBacktrace interface {
	Ref
	Ptr() ScriptBacktrace
}
type RefScriptExtension interface {
	Ref
	Ptr() ScriptExtension
}
type RefSegmentShape2D interface {
	Ref
	Ptr() SegmentShape2D
}
type RefSemaphore interface {
	Ref
	Ptr() Semaphore
}
type RefSeparationRayShape2D interface {
	Ref
	Ptr() SeparationRayShape2D
}
type RefSeparationRayShape3D interface {
	Ref
	Ptr() SeparationRayShape3D
}
type RefShader interface {
	Ref
	Ptr() Shader
}
type RefShaderInclude interface {
	Ref
	Ptr() ShaderInclude
}
type RefShaderMaterial interface {
	Ref
	Ptr() ShaderMaterial
}
type RefShape2D interface {
	Ref
	Ptr() Shape2D
}
type RefShape3D interface {
	Ref
	Ptr() Shape3D
}
type RefShortcut interface {
	Ref
	Ptr() Shortcut
}
type RefSkeletonModification2D interface {
	Ref
	Ptr() SkeletonModification2D
}
type RefSkeletonModification2DCCDIK interface {
	Ref
	Ptr() SkeletonModification2DCCDIK
}
type RefSkeletonModification2DFABRIK interface {
	Ref
	Ptr() SkeletonModification2DFABRIK
}
type RefSkeletonModification2DJiggle interface {
	Ref
	Ptr() SkeletonModification2DJiggle
}
type RefSkeletonModification2DLookAt interface {
	Ref
	Ptr() SkeletonModification2DLookAt
}
type RefSkeletonModification2DPhysicalBones interface {
	Ref
	Ptr() SkeletonModification2DPhysicalBones
}
type RefSkeletonModification2DStackHolder interface {
	Ref
	Ptr() SkeletonModification2DStackHolder
}
type RefSkeletonModification2DTwoBoneIK interface {
	Ref
	Ptr() SkeletonModification2DTwoBoneIK
}
type RefSkeletonModificationStack2D interface {
	Ref
	Ptr() SkeletonModificationStack2D
}
type RefSkeletonProfile interface {
	Ref
	Ptr() SkeletonProfile
}
type RefSkeletonProfileHumanoid interface {
	Ref
	Ptr() SkeletonProfileHumanoid
}
type RefSkin interface {
	Ref
	Ptr() Skin
}
type RefSkinReference interface {
	Ref
	Ptr() SkinReference
}
type RefSky interface {
	Ref
	Ptr() Sky
}
type RefSocketServer interface {
	Ref
	Ptr() SocketServer
}
type RefSphereMesh interface {
	Ref
	Ptr() SphereMesh
}
type RefSphereOccluder3D interface {
	Ref
	Ptr() SphereOccluder3D
}
type RefSphereShape3D interface {
	Ref
	Ptr() SphereShape3D
}
type RefSpriteFrames interface {
	Ref
	Ptr() SpriteFrames
}
type RefStandardMaterial3D interface {
	Ref
	Ptr() StandardMaterial3D
}
type RefStreamPeer interface {
	Ref
	Ptr() StreamPeer
}
type RefStreamPeerBuffer interface {
	Ref
	Ptr() StreamPeerBuffer
}
type RefStreamPeerExtension interface {
	Ref
	Ptr() StreamPeerExtension
}
type RefStreamPeerGZIP interface {
	Ref
	Ptr() StreamPeerGZIP
}
type RefStreamPeerSocket interface {
	Ref
	Ptr() StreamPeerSocket
}
type RefStreamPeerTCP interface {
	Ref
	Ptr() StreamPeerTCP
}
type RefStreamPeerTLS interface {
	Ref
	Ptr() StreamPeerTLS
}
type RefStreamPeerUDS interface {
	Ref
	Ptr() StreamPeerUDS
}
type RefStyleBox interface {
	Ref
	Ptr() StyleBox
}
type RefStyleBoxEmpty interface {
	Ref
	Ptr() StyleBoxEmpty
}
type RefStyleBoxFlat interface {
	Ref
	Ptr() StyleBoxFlat
}
type RefStyleBoxLine interface {
	Ref
	Ptr() StyleBoxLine
}
type RefStyleBoxTexture interface {
	Ref
	Ptr() StyleBoxTexture
}
type RefSubtweenTweener interface {
	Ref
	Ptr() SubtweenTweener
}
type RefSurfaceTool interface {
	Ref
	Ptr() SurfaceTool
}
type RefSyntaxHighlighter interface {
	Ref
	Ptr() SyntaxHighlighter
}
type RefSystemFont interface {
	Ref
	Ptr() SystemFont
}
type RefTCPServer interface {
	Ref
	Ptr() TCPServer
}
type RefTLSOptions interface {
	Ref
	Ptr() TLSOptions
}
type RefTextLine interface {
	Ref
	Ptr() TextLine
}
type RefTextMesh interface {
	Ref
	Ptr() TextMesh
}
type RefTextParagraph interface {
	Ref
	Ptr() TextParagraph
}
type RefTextServer interface {
	Ref
	Ptr() TextServer
}
type RefTextServerAdvanced interface {
	Ref
	Ptr() TextServerAdvanced
}
type RefTextServerDummy interface {
	Ref
	Ptr() TextServerDummy
}
type RefTextServerExtension interface {
	Ref
	Ptr() TextServerExtension
}
type RefTexture interface {
	Ref
	Ptr() Texture
}
type RefTexture2D interface {
	Ref
	Ptr() Texture2D
}
type RefTexture2DArray interface {
	Ref
	Ptr() Texture2DArray
}
type RefTexture2DArrayRD interface {
	Ref
	Ptr() Texture2DArrayRD
}
type RefTexture2DRD interface {
	Ref
	Ptr() Texture2DRD
}
type RefTexture3D interface {
	Ref
	Ptr() Texture3D
}
type RefTexture3DRD interface {
	Ref
	Ptr() Texture3DRD
}
type RefTextureCubemapArrayRD interface {
	Ref
	Ptr() TextureCubemapArrayRD
}
type RefTextureCubemapRD interface {
	Ref
	Ptr() TextureCubemapRD
}
type RefTextureLayered interface {
	Ref
	Ptr() TextureLayered
}
type RefTextureLayeredRD interface {
	Ref
	Ptr() TextureLayeredRD
}
type RefTheme interface {
	Ref
	Ptr() Theme
}
type RefThread interface {
	Ref
	Ptr() Thread
}
type RefTileMapPattern interface {
	Ref
	Ptr() TileMapPattern
}
type RefTileSet interface {
	Ref
	Ptr() TileSet
}
type RefTileSetAtlasSource interface {
	Ref
	Ptr() TileSetAtlasSource
}
type RefTileSetScenesCollectionSource interface {
	Ref
	Ptr() TileSetScenesCollectionSource
}
type RefTileSetSource interface {
	Ref
	Ptr() TileSetSource
}
type RefTorusMesh interface {
	Ref
	Ptr() TorusMesh
}
type RefTranslation interface {
	Ref
	Ptr() Translation
}
type RefTranslationDomain interface {
	Ref
	Ptr() TranslationDomain
}
type RefTriangleMesh interface {
	Ref
	Ptr() TriangleMesh
}
type RefTubeTrailMesh interface {
	Ref
	Ptr() TubeTrailMesh
}
type RefTween interface {
	Ref
	Ptr() Tween
}
type RefTweener interface {
	Ref
	Ptr() Tweener
}
type RefUDPServer interface {
	Ref
	Ptr() UDPServer
}
type RefUDSServer interface {
	Ref
	Ptr() UDSServer
}
type RefUPNP interface {
	Ref
	Ptr() UPNP
}
type RefUPNPDevice interface {
	Ref
	Ptr() UPNPDevice
}
type RefVideoStream interface {
	Ref
	Ptr() VideoStream
}
type RefVideoStreamPlayback interface {
	Ref
	Ptr() VideoStreamPlayback
}
type RefVideoStreamTheora interface {
	Ref
	Ptr() VideoStreamTheora
}
type RefViewportTexture interface {
	Ref
	Ptr() ViewportTexture
}
type RefVisualShader interface {
	Ref
	Ptr() VisualShader
}
type RefVisualShaderNode interface {
	Ref
	Ptr() VisualShaderNode
}
type RefVisualShaderNodeBillboard interface {
	Ref
	Ptr() VisualShaderNodeBillboard
}
type RefVisualShaderNodeBooleanConstant interface {
	Ref
	Ptr() VisualShaderNodeBooleanConstant
}
type RefVisualShaderNodeBooleanParameter interface {
	Ref
	Ptr() VisualShaderNodeBooleanParameter
}
type RefVisualShaderNodeClamp interface {
	Ref
	Ptr() VisualShaderNodeClamp
}
type RefVisualShaderNodeColorConstant interface {
	Ref
	Ptr() VisualShaderNodeColorConstant
}
type RefVisualShaderNodeColorFunc interface {
	Ref
	Ptr() VisualShaderNodeColorFunc
}
type RefVisualShaderNodeColorOp interface {
	Ref
	Ptr() VisualShaderNodeColorOp
}
type RefVisualShaderNodeColorParameter interface {
	Ref
	Ptr() VisualShaderNodeColorParameter
}
type RefVisualShaderNodeComment interface {
	Ref
	Ptr() VisualShaderNodeComment
}
type RefVisualShaderNodeCompare interface {
	Ref
	Ptr() VisualShaderNodeCompare
}
type RefVisualShaderNodeConstant interface {
	Ref
	Ptr() VisualShaderNodeConstant
}
type RefVisualShaderNodeCubemap interface {
	Ref
	Ptr() VisualShaderNodeCubemap
}
type RefVisualShaderNodeCubemapParameter interface {
	Ref
	Ptr() VisualShaderNodeCubemapParameter
}
type RefVisualShaderNodeCurveTexture interface {
	Ref
	Ptr() VisualShaderNodeCurveTexture
}
type RefVisualShaderNodeCurveXYZTexture interface {
	Ref
	Ptr() VisualShaderNodeCurveXYZTexture
}
type RefVisualShaderNodeCustom interface {
	Ref
	Ptr() VisualShaderNodeCustom
}
type RefVisualShaderNodeDerivativeFunc interface {
	Ref
	Ptr() VisualShaderNodeDerivativeFunc
}
type RefVisualShaderNodeDeterminant interface {
	Ref
	Ptr() VisualShaderNodeDeterminant
}
type RefVisualShaderNodeDistanceFade interface {
	Ref
	Ptr() VisualShaderNodeDistanceFade
}
type RefVisualShaderNodeDotProduct interface {
	Ref
	Ptr() VisualShaderNodeDotProduct
}
type RefVisualShaderNodeExpression interface {
	Ref
	Ptr() VisualShaderNodeExpression
}
type RefVisualShaderNodeFaceForward interface {
	Ref
	Ptr() VisualShaderNodeFaceForward
}
type RefVisualShaderNodeFloatConstant interface {
	Ref
	Ptr() VisualShaderNodeFloatConstant
}
type RefVisualShaderNodeFloatFunc interface {
	Ref
	Ptr() VisualShaderNodeFloatFunc
}
type RefVisualShaderNodeFloatOp interface {
	Ref
	Ptr() VisualShaderNodeFloatOp
}
type RefVisualShaderNodeFloatParameter interface {
	Ref
	Ptr() VisualShaderNodeFloatParameter
}
type RefVisualShaderNodeFrame interface {
	Ref
	Ptr() VisualShaderNodeFrame
}
type RefVisualShaderNodeFresnel interface {
	Ref
	Ptr() VisualShaderNodeFresnel
}
type RefVisualShaderNodeGlobalExpression interface {
	Ref
	Ptr() VisualShaderNodeGlobalExpression
}
type RefVisualShaderNodeGroupBase interface {
	Ref
	Ptr() VisualShaderNodeGroupBase
}
type RefVisualShaderNodeIf interface {
	Ref
	Ptr() VisualShaderNodeIf
}
type RefVisualShaderNodeInput interface {
	Ref
	Ptr() VisualShaderNodeInput
}
type RefVisualShaderNodeIntConstant interface {
	Ref
	Ptr() VisualShaderNodeIntConstant
}
type RefVisualShaderNodeIntFunc interface {
	Ref
	Ptr() VisualShaderNodeIntFunc
}
type RefVisualShaderNodeIntOp interface {
	Ref
	Ptr() VisualShaderNodeIntOp
}
type RefVisualShaderNodeIntParameter interface {
	Ref
	Ptr() VisualShaderNodeIntParameter
}
type RefVisualShaderNodeIs interface {
	Ref
	Ptr() VisualShaderNodeIs
}
type RefVisualShaderNodeLinearSceneDepth interface {
	Ref
	Ptr() VisualShaderNodeLinearSceneDepth
}
type RefVisualShaderNodeMix interface {
	Ref
	Ptr() VisualShaderNodeMix
}
type RefVisualShaderNodeMultiplyAdd interface {
	Ref
	Ptr() VisualShaderNodeMultiplyAdd
}
type RefVisualShaderNodeOuterProduct interface {
	Ref
	Ptr() VisualShaderNodeOuterProduct
}
type RefVisualShaderNodeOutput interface {
	Ref
	Ptr() VisualShaderNodeOutput
}
type RefVisualShaderNodeParameter interface {
	Ref
	Ptr() VisualShaderNodeParameter
}
type RefVisualShaderNodeParameterRef interface {
	Ref
	Ptr() VisualShaderNodeParameterRef
}
type RefVisualShaderNodeParticleAccelerator interface {
	Ref
	Ptr() VisualShaderNodeParticleAccelerator
}
type RefVisualShaderNodeParticleBoxEmitter interface {
	Ref
	Ptr() VisualShaderNodeParticleBoxEmitter
}
type RefVisualShaderNodeParticleConeVelocity interface {
	Ref
	Ptr() VisualShaderNodeParticleConeVelocity
}
type RefVisualShaderNodeParticleEmit interface {
	Ref
	Ptr() VisualShaderNodeParticleEmit
}
type RefVisualShaderNodeParticleEmitter interface {
	Ref
	Ptr() VisualShaderNodeParticleEmitter
}
type RefVisualShaderNodeParticleMeshEmitter interface {
	Ref
	Ptr() VisualShaderNodeParticleMeshEmitter
}
type RefVisualShaderNodeParticleMultiplyByAxisAngle interface {
	Ref
	Ptr() VisualShaderNodeParticleMultiplyByAxisAngle
}
type RefVisualShaderNodeParticleOutput interface {
	Ref
	Ptr() VisualShaderNodeParticleOutput
}
type RefVisualShaderNodeParticleRandomness interface {
	Ref
	Ptr() VisualShaderNodeParticleRandomness
}
type RefVisualShaderNodeParticleRingEmitter interface {
	Ref
	Ptr() VisualShaderNodeParticleRingEmitter
}
type RefVisualShaderNodeParticleSphereEmitter interface {
	Ref
	Ptr() VisualShaderNodeParticleSphereEmitter
}
type RefVisualShaderNodeProximityFade interface {
	Ref
	Ptr() VisualShaderNodeProximityFade
}
type RefVisualShaderNodeRandomRange interface {
	Ref
	Ptr() VisualShaderNodeRandomRange
}
type RefVisualShaderNodeRemap interface {
	Ref
	Ptr() VisualShaderNodeRemap
}
type RefVisualShaderNodeReroute interface {
	Ref
	Ptr() VisualShaderNodeReroute
}
type RefVisualShaderNodeResizableBase interface {
	Ref
	Ptr() VisualShaderNodeResizableBase
}
type RefVisualShaderNodeRotationByAxis interface {
	Ref
	Ptr() VisualShaderNodeRotationByAxis
}
type RefVisualShaderNodeSDFRaymarch interface {
	Ref
	Ptr() VisualShaderNodeSDFRaymarch
}
type RefVisualShaderNodeSDFToScreenUV interface {
	Ref
	Ptr() VisualShaderNodeSDFToScreenUV
}
type RefVisualShaderNodeSample3D interface {
	Ref
	Ptr() VisualShaderNodeSample3D
}
type RefVisualShaderNodeScreenNormalWorldSpace interface {
	Ref
	Ptr() VisualShaderNodeScreenNormalWorldSpace
}
type RefVisualShaderNodeScreenUVToSDF interface {
	Ref
	Ptr() VisualShaderNodeScreenUVToSDF
}
type RefVisualShaderNodeSmoothStep interface {
	Ref
	Ptr() VisualShaderNodeSmoothStep
}
type RefVisualShaderNodeStep interface {
	Ref
	Ptr() VisualShaderNodeStep
}
type RefVisualShaderNodeSwitch interface {
	Ref
	Ptr() VisualShaderNodeSwitch
}
type RefVisualShaderNodeTexture interface {
	Ref
	Ptr() VisualShaderNodeTexture
}
type RefVisualShaderNodeTexture2DArray interface {
	Ref
	Ptr() VisualShaderNodeTexture2DArray
}
type RefVisualShaderNodeTexture2DArrayParameter interface {
	Ref
	Ptr() VisualShaderNodeTexture2DArrayParameter
}
type RefVisualShaderNodeTexture2DParameter interface {
	Ref
	Ptr() VisualShaderNodeTexture2DParameter
}
type RefVisualShaderNodeTexture3D interface {
	Ref
	Ptr() VisualShaderNodeTexture3D
}
type RefVisualShaderNodeTexture3DParameter interface {
	Ref
	Ptr() VisualShaderNodeTexture3DParameter
}
type RefVisualShaderNodeTextureParameter interface {
	Ref
	Ptr() VisualShaderNodeTextureParameter
}
type RefVisualShaderNodeTextureParameterTriplanar interface {
	Ref
	Ptr() VisualShaderNodeTextureParameterTriplanar
}
type RefVisualShaderNodeTextureSDF interface {
	Ref
	Ptr() VisualShaderNodeTextureSDF
}
type RefVisualShaderNodeTextureSDFNormal interface {
	Ref
	Ptr() VisualShaderNodeTextureSDFNormal
}
type RefVisualShaderNodeTransformCompose interface {
	Ref
	Ptr() VisualShaderNodeTransformCompose
}
type RefVisualShaderNodeTransformConstant interface {
	Ref
	Ptr() VisualShaderNodeTransformConstant
}
type RefVisualShaderNodeTransformDecompose interface {
	Ref
	Ptr() VisualShaderNodeTransformDecompose
}
type RefVisualShaderNodeTransformFunc interface {
	Ref
	Ptr() VisualShaderNodeTransformFunc
}
type RefVisualShaderNodeTransformOp interface {
	Ref
	Ptr() VisualShaderNodeTransformOp
}
type RefVisualShaderNodeTransformParameter interface {
	Ref
	Ptr() VisualShaderNodeTransformParameter
}
type RefVisualShaderNodeTransformVecMult interface {
	Ref
	Ptr() VisualShaderNodeTransformVecMult
}
type RefVisualShaderNodeUIntConstant interface {
	Ref
	Ptr() VisualShaderNodeUIntConstant
}
type RefVisualShaderNodeUIntFunc interface {
	Ref
	Ptr() VisualShaderNodeUIntFunc
}
type RefVisualShaderNodeUIntOp interface {
	Ref
	Ptr() VisualShaderNodeUIntOp
}
type RefVisualShaderNodeUIntParameter interface {
	Ref
	Ptr() VisualShaderNodeUIntParameter
}
type RefVisualShaderNodeUVFunc interface {
	Ref
	Ptr() VisualShaderNodeUVFunc
}
type RefVisualShaderNodeUVPolarCoord interface {
	Ref
	Ptr() VisualShaderNodeUVPolarCoord
}
type RefVisualShaderNodeVarying interface {
	Ref
	Ptr() VisualShaderNodeVarying
}
type RefVisualShaderNodeVaryingGetter interface {
	Ref
	Ptr() VisualShaderNodeVaryingGetter
}
type RefVisualShaderNodeVaryingSetter interface {
	Ref
	Ptr() VisualShaderNodeVaryingSetter
}
type RefVisualShaderNodeVec2Constant interface {
	Ref
	Ptr() VisualShaderNodeVec2Constant
}
type RefVisualShaderNodeVec2Parameter interface {
	Ref
	Ptr() VisualShaderNodeVec2Parameter
}
type RefVisualShaderNodeVec3Constant interface {
	Ref
	Ptr() VisualShaderNodeVec3Constant
}
type RefVisualShaderNodeVec3Parameter interface {
	Ref
	Ptr() VisualShaderNodeVec3Parameter
}
type RefVisualShaderNodeVec4Constant interface {
	Ref
	Ptr() VisualShaderNodeVec4Constant
}
type RefVisualShaderNodeVec4Parameter interface {
	Ref
	Ptr() VisualShaderNodeVec4Parameter
}
type RefVisualShaderNodeVectorBase interface {
	Ref
	Ptr() VisualShaderNodeVectorBase
}
type RefVisualShaderNodeVectorCompose interface {
	Ref
	Ptr() VisualShaderNodeVectorCompose
}
type RefVisualShaderNodeVectorDecompose interface {
	Ref
	Ptr() VisualShaderNodeVectorDecompose
}
type RefVisualShaderNodeVectorDistance interface {
	Ref
	Ptr() VisualShaderNodeVectorDistance
}
type RefVisualShaderNodeVectorFunc interface {
	Ref
	Ptr() VisualShaderNodeVectorFunc
}
type RefVisualShaderNodeVectorLen interface {
	Ref
	Ptr() VisualShaderNodeVectorLen
}
type RefVisualShaderNodeVectorOp interface {
	Ref
	Ptr() VisualShaderNodeVectorOp
}
type RefVisualShaderNodeVectorRefract interface {
	Ref
	Ptr() VisualShaderNodeVectorRefract
}
type RefVisualShaderNodeWorldPositionFromDepth interface {
	Ref
	Ptr() VisualShaderNodeWorldPositionFromDepth
}
type RefVoxelGIData interface {
	Ref
	Ptr() VoxelGIData
}
type RefWeakRef interface {
	Ref
	Ptr() WeakRef
}
type RefWebRTCDataChannel interface {
	Ref
	Ptr() WebRTCDataChannel
}
type RefWebRTCDataChannelExtension interface {
	Ref
	Ptr() WebRTCDataChannelExtension
}
type RefWebRTCMultiplayerPeer interface {
	Ref
	Ptr() WebRTCMultiplayerPeer
}
type RefWebRTCPeerConnection interface {
	Ref
	Ptr() WebRTCPeerConnection
}
type RefWebRTCPeerConnectionExtension interface {
	Ref
	Ptr() WebRTCPeerConnectionExtension
}
type RefWebSocketMultiplayerPeer interface {
	Ref
	Ptr() WebSocketMultiplayerPeer
}
type RefWebSocketPeer interface {
	Ref
	Ptr() WebSocketPeer
}
type RefWebXRInterface interface {
	Ref
	Ptr() WebXRInterface
}
type RefWorld2D interface {
	Ref
	Ptr() World2D
}
type RefWorld3D interface {
	Ref
	Ptr() World3D
}
type RefWorldBoundaryShape2D interface {
	Ref
	Ptr() WorldBoundaryShape2D
}
type RefWorldBoundaryShape3D interface {
	Ref
	Ptr() WorldBoundaryShape3D
}
type RefX509Certificate interface {
	Ref
	Ptr() X509Certificate
}
type RefXMLParser interface {
	Ref
	Ptr() XMLParser
}
type RefXRBodyTracker interface {
	Ref
	Ptr() XRBodyTracker
}
type RefXRControllerTracker interface {
	Ref
	Ptr() XRControllerTracker
}
type RefXRFaceTracker interface {
	Ref
	Ptr() XRFaceTracker
}
type RefXRHandTracker interface {
	Ref
	Ptr() XRHandTracker
}
type RefXRInterface interface {
	Ref
	Ptr() XRInterface
}
type RefXRInterfaceExtension interface {
	Ref
	Ptr() XRInterfaceExtension
}
type RefXRPose interface {
	Ref
	Ptr() XRPose
}
type RefXRPositionalTracker interface {
	Ref
	Ptr() XRPositionalTracker
}
type RefXRTracker interface {
	Ref
	Ptr() XRTracker
}
type RefZIPPacker interface {
	Ref
	Ptr() ZIPPacker
}
type RefZIPReader interface {
	Ref
	Ptr() ZIPReader
}
