/*------------------------------------------------------------------------------
//   This code was generated by template ffi_wrapper.c.tmpl.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "ffi_wrapper.h.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/
#include "ffi_wrapper.gen.h"
#include "stacktrace.h"
#include <godot/gdextension_interface.h>

/* Go cannot call C function pointers directly, so we must generate C wrapper
 * code to call the functions. */

void cgo_callfn_GDExtensionVariantFromTypeConstructorFunc(
    const GDExtensionVariantFromTypeConstructorFunc fn,
    GDExtensionVariantPtr arg_0, GDExtensionTypePtr arg_1) {
  printStacktrace();
  fn(arg_0, arg_1);
}
void cgo_callfn_GDExtensionTypeFromVariantConstructorFunc(
    const GDExtensionTypeFromVariantConstructorFunc fn,
    GDExtensionTypePtr arg_0, GDExtensionVariantPtr arg_1) {
  printStacktrace();
  fn(arg_0, arg_1);
}
void cgo_callfn_GDExtensionPtrOperatorEvaluator(
    const GDExtensionPtrOperatorEvaluator fn, GDExtensionConstTypePtr p_left,
    GDExtensionConstTypePtr p_right, GDExtensionTypePtr r_result) {
  printStacktrace();
  fn(p_left, p_right, r_result);
}
void cgo_callfn_GDExtensionPtrBuiltInMethod(
    const GDExtensionPtrBuiltInMethod fn, GDExtensionTypePtr p_base,
    const GDExtensionConstTypePtr *p_args, GDExtensionTypePtr r_return,
    int p_argument_count) {
  printStacktrace();
  fn(p_base, p_args, r_return, p_argument_count);
}
void cgo_callfn_GDExtensionPtrConstructor(
    const GDExtensionPtrConstructor fn, GDExtensionTypePtr p_base,
    const GDExtensionConstTypePtr *p_args) {
  printStacktrace();
  fn(p_base, p_args);
}
void cgo_callfn_GDExtensionPtrDestructor(const GDExtensionPtrDestructor fn,
                                         GDExtensionTypePtr p_base) {
  printStacktrace();
  fn(p_base);
}
void cgo_callfn_GDExtensionPtrSetter(const GDExtensionPtrSetter fn,
                                     GDExtensionTypePtr p_base,
                                     GDExtensionConstTypePtr p_value) {
  printStacktrace();
  fn(p_base, p_value);
}
void cgo_callfn_GDExtensionPtrGetter(const GDExtensionPtrGetter fn,
                                     GDExtensionConstTypePtr p_base,
                                     GDExtensionTypePtr r_value) {
  printStacktrace();
  fn(p_base, r_value);
}
void cgo_callfn_GDExtensionPtrIndexedSetter(
    const GDExtensionPtrIndexedSetter fn, GDExtensionTypePtr p_base,
    GDExtensionInt p_index, GDExtensionConstTypePtr p_value) {
  printStacktrace();
  fn(p_base, p_index, p_value);
}
void cgo_callfn_GDExtensionPtrIndexedGetter(
    const GDExtensionPtrIndexedGetter fn, GDExtensionConstTypePtr p_base,
    GDExtensionInt p_index, GDExtensionTypePtr r_value) {
  printStacktrace();
  fn(p_base, p_index, r_value);
}
void cgo_callfn_GDExtensionPtrKeyedSetter(const GDExtensionPtrKeyedSetter fn,
                                          GDExtensionTypePtr p_base,
                                          GDExtensionConstTypePtr p_key,
                                          GDExtensionConstTypePtr p_value) {
  printStacktrace();
  fn(p_base, p_key, p_value);
}
void cgo_callfn_GDExtensionPtrKeyedGetter(const GDExtensionPtrKeyedGetter fn,
                                          GDExtensionConstTypePtr p_base,
                                          GDExtensionConstTypePtr p_key,
                                          GDExtensionTypePtr r_value) {
  printStacktrace();
  fn(p_base, p_key, r_value);
}
uint32_t
cgo_callfn_GDExtensionPtrKeyedChecker(const GDExtensionPtrKeyedChecker fn,
                                      GDExtensionConstVariantPtr p_base,
                                      GDExtensionConstVariantPtr p_key) {
  printStacktrace();
  return fn(p_base, p_key);
}
void cgo_callfn_GDExtensionPtrUtilityFunction(
    const GDExtensionPtrUtilityFunction fn, GDExtensionTypePtr r_return,
    const GDExtensionConstTypePtr *p_args, int p_argument_count) {
  printStacktrace();
  fn(r_return, p_args, p_argument_count);
}
GDExtensionObjectPtr
cgo_callfn_GDExtensionClassConstructor(const GDExtensionClassConstructor fn) {
  printStacktrace();
  return fn();
}
void *cgo_callfn_GDExtensionInstanceBindingCreateCallback(
    const GDExtensionInstanceBindingCreateCallback fn, void *p_token,
    void *p_instance) {
  printStacktrace();
  return fn(p_token, p_instance);
}
void cgo_callfn_GDExtensionInstanceBindingFreeCallback(
    const GDExtensionInstanceBindingFreeCallback fn, void *p_token,
    void *p_instance, void *p_binding) {
  printStacktrace();
  fn(p_token, p_instance, p_binding);
}
GDExtensionBool cgo_callfn_GDExtensionInstanceBindingReferenceCallback(
    const GDExtensionInstanceBindingReferenceCallback fn, void *p_token,
    void *p_binding, GDExtensionBool p_reference) {
  printStacktrace();
  return fn(p_token, p_binding, p_reference);
}
GDExtensionBool cgo_callfn_GDExtensionClassSet(
    const GDExtensionClassSet fn, GDExtensionClassInstancePtr p_instance,
    GDExtensionConstStringNamePtr p_name, GDExtensionConstVariantPtr p_value) {
  printStacktrace();
  return fn(p_instance, p_name, p_value);
}
GDExtensionBool cgo_callfn_GDExtensionClassGet(
    const GDExtensionClassGet fn, GDExtensionClassInstancePtr p_instance,
    GDExtensionConstStringNamePtr p_name, GDExtensionVariantPtr r_ret) {
  printStacktrace();
  return fn(p_instance, p_name, r_ret);
}
uint64_t
cgo_callfn_GDExtensionClassGetRID(const GDExtensionClassGetRID fn,
                                  GDExtensionClassInstancePtr p_instance) {
  printStacktrace();
  return fn(p_instance);
}
const GDExtensionPropertyInfo *cgo_callfn_GDExtensionClassGetPropertyList(
    const GDExtensionClassGetPropertyList fn,
    GDExtensionClassInstancePtr p_instance, uint32_t *r_count) {
  printStacktrace();
  return fn(p_instance, r_count);
}
void cgo_callfn_GDExtensionClassFreePropertyList(
    const GDExtensionClassFreePropertyList fn,
    GDExtensionClassInstancePtr p_instance,
    const GDExtensionPropertyInfo *p_list) {
  printStacktrace();
  fn(p_instance, p_list);
}
GDExtensionBool cgo_callfn_GDExtensionClassPropertyCanRevert(
    const GDExtensionClassPropertyCanRevert fn,
    GDExtensionClassInstancePtr p_instance,
    GDExtensionConstStringNamePtr p_name) {
  printStacktrace();
  return fn(p_instance, p_name);
}
GDExtensionBool cgo_callfn_GDExtensionClassPropertyGetRevert(
    const GDExtensionClassPropertyGetRevert fn,
    GDExtensionClassInstancePtr p_instance,
    GDExtensionConstStringNamePtr p_name, GDExtensionVariantPtr r_ret) {
  printStacktrace();
  return fn(p_instance, p_name, r_ret);
}
void cgo_callfn_GDExtensionClassNotification(
    const GDExtensionClassNotification fn,
    GDExtensionClassInstancePtr p_instance, int32_t p_what) {
  printStacktrace();
  fn(p_instance, p_what);
}
void cgo_callfn_GDExtensionClassToString(const GDExtensionClassToString fn,
                                         GDExtensionClassInstancePtr p_instance,
                                         GDExtensionBool *r_is_valid,
                                         GDExtensionStringPtr p_out) {
  printStacktrace();
  fn(p_instance, r_is_valid, p_out);
}
void cgo_callfn_GDExtensionClassReference(
    const GDExtensionClassReference fn,
    GDExtensionClassInstancePtr p_instance) {
  printStacktrace();
  fn(p_instance);
}
void cgo_callfn_GDExtensionClassUnreference(
    const GDExtensionClassUnreference fn,
    GDExtensionClassInstancePtr p_instance) {
  printStacktrace();
  fn(p_instance);
}
void cgo_callfn_GDExtensionClassCallVirtual(
    const GDExtensionClassCallVirtual fn,
    GDExtensionClassInstancePtr p_instance,
    const GDExtensionConstTypePtr *p_args, GDExtensionTypePtr r_ret) {
  printStacktrace();
  fn(p_instance, p_args, r_ret);
}
GDExtensionObjectPtr cgo_callfn_GDExtensionClassCreateInstance(
    const GDExtensionClassCreateInstance fn, void *p_userdata) {
  printStacktrace();
  return fn(p_userdata);
}
void cgo_callfn_GDExtensionClassFreeInstance(
    const GDExtensionClassFreeInstance fn, void *p_userdata,
    GDExtensionClassInstancePtr p_instance) {
  printStacktrace();
  fn(p_userdata, p_instance);
}
GDExtensionClassCallVirtual
cgo_callfn_GDExtensionClassGetVirtual(const GDExtensionClassGetVirtual fn,
                                      void *p_userdata,
                                      GDExtensionConstStringNamePtr p_name) {
  printStacktrace();
  return fn(p_userdata, p_name);
}
void cgo_callfn_GDExtensionClassMethodCall(
    const GDExtensionClassMethodCall fn, void *method_userdata,
    GDExtensionClassInstancePtr p_instance,
    const GDExtensionConstVariantPtr *p_args, GDExtensionInt p_argument_count,
    GDExtensionVariantPtr r_return, GDExtensionCallError *r_error) {
  printStacktrace();
  fn(method_userdata, p_instance, p_args, p_argument_count, r_return, r_error);
}
void cgo_callfn_GDExtensionClassMethodPtrCall(
    const GDExtensionClassMethodPtrCall fn, void *method_userdata,
    GDExtensionClassInstancePtr p_instance,
    const GDExtensionConstTypePtr *p_args, GDExtensionTypePtr r_ret) {
  printStacktrace();
  fn(method_userdata, p_instance, p_args, r_ret);
}
GDExtensionBool cgo_callfn_GDExtensionScriptInstanceSet(
    const GDExtensionScriptInstanceSet fn,
    GDExtensionScriptInstanceDataPtr p_instance,
    GDExtensionConstStringNamePtr p_name, GDExtensionConstVariantPtr p_value) {
  printStacktrace();
  return fn(p_instance, p_name, p_value);
}
GDExtensionBool cgo_callfn_GDExtensionScriptInstanceGet(
    const GDExtensionScriptInstanceGet fn,
    GDExtensionScriptInstanceDataPtr p_instance,
    GDExtensionConstStringNamePtr p_name, GDExtensionVariantPtr r_ret) {
  printStacktrace();
  return fn(p_instance, p_name, r_ret);
}
const GDExtensionPropertyInfo *
cgo_callfn_GDExtensionScriptInstanceGetPropertyList(
    const GDExtensionScriptInstanceGetPropertyList fn,
    GDExtensionScriptInstanceDataPtr p_instance, uint32_t *r_count) {
  printStacktrace();
  return fn(p_instance, r_count);
}
void cgo_callfn_GDExtensionScriptInstanceFreePropertyList(
    const GDExtensionScriptInstanceFreePropertyList fn,
    GDExtensionScriptInstanceDataPtr p_instance,
    const GDExtensionPropertyInfo *p_list) {
  printStacktrace();
  fn(p_instance, p_list);
}
GDExtensionVariantType cgo_callfn_GDExtensionScriptInstanceGetPropertyType(
    const GDExtensionScriptInstanceGetPropertyType fn,
    GDExtensionScriptInstanceDataPtr p_instance,
    GDExtensionConstStringNamePtr p_name, GDExtensionBool *r_is_valid) {
  printStacktrace();
  return fn(p_instance, p_name, r_is_valid);
}
GDExtensionBool cgo_callfn_GDExtensionScriptInstancePropertyCanRevert(
    const GDExtensionScriptInstancePropertyCanRevert fn,
    GDExtensionScriptInstanceDataPtr p_instance,
    GDExtensionConstStringNamePtr p_name) {
  printStacktrace();
  return fn(p_instance, p_name);
}
GDExtensionBool cgo_callfn_GDExtensionScriptInstancePropertyGetRevert(
    const GDExtensionScriptInstancePropertyGetRevert fn,
    GDExtensionScriptInstanceDataPtr p_instance,
    GDExtensionConstStringNamePtr p_name, GDExtensionVariantPtr r_ret) {
  printStacktrace();
  return fn(p_instance, p_name, r_ret);
}
GDExtensionObjectPtr cgo_callfn_GDExtensionScriptInstanceGetOwner(
    const GDExtensionScriptInstanceGetOwner fn,
    GDExtensionScriptInstanceDataPtr p_instance) {
  printStacktrace();
  return fn(p_instance);
}
void cgo_callfn_GDExtensionScriptInstancePropertyStateAdd(
    const GDExtensionScriptInstancePropertyStateAdd fn,
    GDExtensionConstStringNamePtr p_name, GDExtensionConstVariantPtr p_value,
    void *p_userdata) {
  printStacktrace();
  fn(p_name, p_value, p_userdata);
}
void cgo_callfn_GDExtensionScriptInstanceGetPropertyState(
    const GDExtensionScriptInstanceGetPropertyState fn,
    GDExtensionScriptInstanceDataPtr p_instance,
    GDExtensionScriptInstancePropertyStateAdd p_add_func, void *p_userdata) {
  printStacktrace();
  fn(p_instance, p_add_func, p_userdata);
}
const GDExtensionMethodInfo *cgo_callfn_GDExtensionScriptInstanceGetMethodList(
    const GDExtensionScriptInstanceGetMethodList fn,
    GDExtensionScriptInstanceDataPtr p_instance, uint32_t *r_count) {
  printStacktrace();
  return fn(p_instance, r_count);
}
void cgo_callfn_GDExtensionScriptInstanceFreeMethodList(
    const GDExtensionScriptInstanceFreeMethodList fn,
    GDExtensionScriptInstanceDataPtr p_instance,
    const GDExtensionMethodInfo *p_list) {
  printStacktrace();
  fn(p_instance, p_list);
}
GDExtensionBool cgo_callfn_GDExtensionScriptInstanceHasMethod(
    const GDExtensionScriptInstanceHasMethod fn,
    GDExtensionScriptInstanceDataPtr p_instance,
    GDExtensionConstStringNamePtr p_name) {
  printStacktrace();
  return fn(p_instance, p_name);
}
void cgo_callfn_GDExtensionScriptInstanceCall(
    const GDExtensionScriptInstanceCall fn,
    GDExtensionScriptInstanceDataPtr p_self,
    GDExtensionConstStringNamePtr p_method,
    const GDExtensionConstVariantPtr *p_args, GDExtensionInt p_argument_count,
    GDExtensionVariantPtr r_return, GDExtensionCallError *r_error) {
  printStacktrace();
  fn(p_self, p_method, p_args, p_argument_count, r_return, r_error);
}
void cgo_callfn_GDExtensionScriptInstanceNotification(
    const GDExtensionScriptInstanceNotification fn,
    GDExtensionScriptInstanceDataPtr p_instance, int32_t p_what) {
  printStacktrace();
  fn(p_instance, p_what);
}
void cgo_callfn_GDExtensionScriptInstanceToString(
    const GDExtensionScriptInstanceToString fn,
    GDExtensionScriptInstanceDataPtr p_instance, GDExtensionBool *r_is_valid,
    GDExtensionStringPtr r_out) {
  printStacktrace();
  fn(p_instance, r_is_valid, r_out);
}
void cgo_callfn_GDExtensionScriptInstanceRefCountIncremented(
    const GDExtensionScriptInstanceRefCountIncremented fn,
    GDExtensionScriptInstanceDataPtr p_instance) {
  printStacktrace();
  fn(p_instance);
}
GDExtensionBool cgo_callfn_GDExtensionScriptInstanceRefCountDecremented(
    const GDExtensionScriptInstanceRefCountDecremented fn,
    GDExtensionScriptInstanceDataPtr p_instance) {
  printStacktrace();
  return fn(p_instance);
}
GDExtensionObjectPtr cgo_callfn_GDExtensionScriptInstanceGetScript(
    const GDExtensionScriptInstanceGetScript fn,
    GDExtensionScriptInstanceDataPtr p_instance) {
  printStacktrace();
  return fn(p_instance);
}
GDExtensionBool cgo_callfn_GDExtensionScriptInstanceIsPlaceholder(
    const GDExtensionScriptInstanceIsPlaceholder fn,
    GDExtensionScriptInstanceDataPtr p_instance) {
  printStacktrace();
  return fn(p_instance);
}
GDExtensionScriptLanguagePtr cgo_callfn_GDExtensionScriptInstanceGetLanguage(
    const GDExtensionScriptInstanceGetLanguage fn,
    GDExtensionScriptInstanceDataPtr p_instance) {
  printStacktrace();
  return fn(p_instance);
}
void cgo_callfn_GDExtensionScriptInstanceFree(
    const GDExtensionScriptInstanceFree fn,
    GDExtensionScriptInstanceDataPtr p_instance) {
  printStacktrace();
  fn(p_instance);
}
GDExtensionBool cgo_callfn_GDExtensionInitializationFunction(
    const GDExtensionInitializationFunction fn,
    const GDExtensionInterface *p_interface,
    GDExtensionClassLibraryPtr p_library,
    GDExtensionInitialization *r_initialization) {
  printStacktrace();
  return fn(p_interface, p_library, r_initialization);
}
/* struct (7) GDExtensionInterface */
void *
cgo_callfn_GDExtensionInterface_mem_alloc(const GDExtensionInterface *p_struct,
                                          size_t p_bytes) {
  return p_struct->mem_alloc(p_bytes);
}
void *cgo_callfn_GDExtensionInterface_mem_realloc(
    const GDExtensionInterface *p_struct, void *p_ptr, size_t p_bytes) {
  return p_struct->mem_realloc(p_ptr, p_bytes);
}
void cgo_callfn_GDExtensionInterface_mem_free(
    const GDExtensionInterface *p_struct, void *p_ptr) {
  p_struct->mem_free(p_ptr);
}
void cgo_callfn_GDExtensionInterface_print_error(
    const GDExtensionInterface *p_struct, const char *p_description,
    const char *p_function, const char *p_file, int32_t p_line) {
  p_struct->print_error(p_description, p_function, p_file, p_line);
}
void cgo_callfn_GDExtensionInterface_print_warning(
    const GDExtensionInterface *p_struct, const char *p_description,
    const char *p_function, const char *p_file, int32_t p_line) {
  p_struct->print_warning(p_description, p_function, p_file, p_line);
}
void cgo_callfn_GDExtensionInterface_print_script_error(
    const GDExtensionInterface *p_struct, const char *p_description,
    const char *p_function, const char *p_file, int32_t p_line) {
  p_struct->print_script_error(p_description, p_function, p_file, p_line);
}
uint64_t cgo_callfn_GDExtensionInterface_get_native_struct_size(
    const GDExtensionInterface *p_struct,
    GDExtensionConstStringNamePtr p_name) {
  return p_struct->get_native_struct_size(p_name);
}
void cgo_callfn_GDExtensionInterface_variant_new_copy(
    const GDExtensionInterface *p_struct, GDExtensionVariantPtr r_dest,
    GDExtensionConstVariantPtr p_src) {
  p_struct->variant_new_copy(r_dest, p_src);
}
void cgo_callfn_GDExtensionInterface_variant_new_nil(
    const GDExtensionInterface *p_struct, GDExtensionVariantPtr r_dest) {
  p_struct->variant_new_nil(r_dest);
}
void cgo_callfn_GDExtensionInterface_variant_destroy(
    const GDExtensionInterface *p_struct, GDExtensionVariantPtr p_self) {
  p_struct->variant_destroy(p_self);
}
void cgo_callfn_GDExtensionInterface_variant_call(
    const GDExtensionInterface *p_struct, GDExtensionVariantPtr p_self,
    GDExtensionConstStringNamePtr p_method,
    const GDExtensionConstVariantPtr *p_args, GDExtensionInt p_argument_count,
    GDExtensionVariantPtr r_return, GDExtensionCallError *r_error) {
  p_struct->variant_call(p_self, p_method, p_args, p_argument_count, r_return,
                         r_error);
}
void cgo_callfn_GDExtensionInterface_variant_call_static(
    const GDExtensionInterface *p_struct, GDExtensionVariantType p_type,
    GDExtensionConstStringNamePtr p_method,
    const GDExtensionConstVariantPtr *p_args, GDExtensionInt p_argument_count,
    GDExtensionVariantPtr r_return, GDExtensionCallError *r_error) {
  p_struct->variant_call_static(p_type, p_method, p_args, p_argument_count,
                                r_return, r_error);
}
void cgo_callfn_GDExtensionInterface_variant_evaluate(
    const GDExtensionInterface *p_struct, GDExtensionVariantOperator p_op,
    GDExtensionConstVariantPtr p_a, GDExtensionConstVariantPtr p_b,
    GDExtensionVariantPtr r_return, GDExtensionBool *r_valid) {
  p_struct->variant_evaluate(p_op, p_a, p_b, r_return, r_valid);
}
void cgo_callfn_GDExtensionInterface_variant_set(
    const GDExtensionInterface *p_struct, GDExtensionVariantPtr p_self,
    GDExtensionConstVariantPtr p_key, GDExtensionConstVariantPtr p_value,
    GDExtensionBool *r_valid) {
  p_struct->variant_set(p_self, p_key, p_value, r_valid);
}
void cgo_callfn_GDExtensionInterface_variant_set_named(
    const GDExtensionInterface *p_struct, GDExtensionVariantPtr p_self,
    GDExtensionConstStringNamePtr p_key, GDExtensionConstVariantPtr p_value,
    GDExtensionBool *r_valid) {
  p_struct->variant_set_named(p_self, p_key, p_value, r_valid);
}
void cgo_callfn_GDExtensionInterface_variant_set_keyed(
    const GDExtensionInterface *p_struct, GDExtensionVariantPtr p_self,
    GDExtensionConstVariantPtr p_key, GDExtensionConstVariantPtr p_value,
    GDExtensionBool *r_valid) {
  p_struct->variant_set_keyed(p_self, p_key, p_value, r_valid);
}
void cgo_callfn_GDExtensionInterface_variant_set_indexed(
    const GDExtensionInterface *p_struct, GDExtensionVariantPtr p_self,
    GDExtensionInt p_index, GDExtensionConstVariantPtr p_value,
    GDExtensionBool *r_valid, GDExtensionBool *r_oob) {
  p_struct->variant_set_indexed(p_self, p_index, p_value, r_valid, r_oob);
}
void cgo_callfn_GDExtensionInterface_variant_get(
    const GDExtensionInterface *p_struct, GDExtensionConstVariantPtr p_self,
    GDExtensionConstVariantPtr p_key, GDExtensionVariantPtr r_ret,
    GDExtensionBool *r_valid) {
  p_struct->variant_get(p_self, p_key, r_ret, r_valid);
}
void cgo_callfn_GDExtensionInterface_variant_get_named(
    const GDExtensionInterface *p_struct, GDExtensionConstVariantPtr p_self,
    GDExtensionConstStringNamePtr p_key, GDExtensionVariantPtr r_ret,
    GDExtensionBool *r_valid) {
  p_struct->variant_get_named(p_self, p_key, r_ret, r_valid);
}
void cgo_callfn_GDExtensionInterface_variant_get_keyed(
    const GDExtensionInterface *p_struct, GDExtensionConstVariantPtr p_self,
    GDExtensionConstVariantPtr p_key, GDExtensionVariantPtr r_ret,
    GDExtensionBool *r_valid) {
  p_struct->variant_get_keyed(p_self, p_key, r_ret, r_valid);
}
void cgo_callfn_GDExtensionInterface_variant_get_indexed(
    const GDExtensionInterface *p_struct, GDExtensionConstVariantPtr p_self,
    GDExtensionInt p_index, GDExtensionVariantPtr r_ret,
    GDExtensionBool *r_valid, GDExtensionBool *r_oob) {
  p_struct->variant_get_indexed(p_self, p_index, r_ret, r_valid, r_oob);
}
GDExtensionBool cgo_callfn_GDExtensionInterface_variant_iter_init(
    const GDExtensionInterface *p_struct, GDExtensionConstVariantPtr p_self,
    GDExtensionVariantPtr r_iter, GDExtensionBool *r_valid) {
  return p_struct->variant_iter_init(p_self, r_iter, r_valid);
}
GDExtensionBool cgo_callfn_GDExtensionInterface_variant_iter_next(
    const GDExtensionInterface *p_struct, GDExtensionConstVariantPtr p_self,
    GDExtensionVariantPtr r_iter, GDExtensionBool *r_valid) {
  return p_struct->variant_iter_next(p_self, r_iter, r_valid);
}
void cgo_callfn_GDExtensionInterface_variant_iter_get(
    const GDExtensionInterface *p_struct, GDExtensionConstVariantPtr p_self,
    GDExtensionVariantPtr r_iter, GDExtensionVariantPtr r_ret,
    GDExtensionBool *r_valid) {
  p_struct->variant_iter_get(p_self, r_iter, r_ret, r_valid);
}
GDExtensionInt cgo_callfn_GDExtensionInterface_variant_hash(
    const GDExtensionInterface *p_struct, GDExtensionConstVariantPtr p_self) {
  return p_struct->variant_hash(p_self);
}
GDExtensionInt cgo_callfn_GDExtensionInterface_variant_recursive_hash(
    const GDExtensionInterface *p_struct, GDExtensionConstVariantPtr p_self,
    GDExtensionInt p_recursion_count) {
  return p_struct->variant_recursive_hash(p_self, p_recursion_count);
}
GDExtensionBool cgo_callfn_GDExtensionInterface_variant_hash_compare(
    const GDExtensionInterface *p_struct, GDExtensionConstVariantPtr p_self,
    GDExtensionConstVariantPtr p_other) {
  return p_struct->variant_hash_compare(p_self, p_other);
}
GDExtensionBool cgo_callfn_GDExtensionInterface_variant_booleanize(
    const GDExtensionInterface *p_struct, GDExtensionConstVariantPtr p_self) {
  return p_struct->variant_booleanize(p_self);
}
void cgo_callfn_GDExtensionInterface_variant_duplicate(
    const GDExtensionInterface *p_struct, GDExtensionConstVariantPtr p_self,
    GDExtensionVariantPtr r_ret, GDExtensionBool p_deep) {
  p_struct->variant_duplicate(p_self, r_ret, p_deep);
}
void cgo_callfn_GDExtensionInterface_variant_stringify(
    const GDExtensionInterface *p_struct, GDExtensionConstVariantPtr p_self,
    GDExtensionStringPtr r_ret) {
  p_struct->variant_stringify(p_self, r_ret);
}
GDExtensionVariantType cgo_callfn_GDExtensionInterface_variant_get_type(
    const GDExtensionInterface *p_struct, GDExtensionConstVariantPtr p_self) {
  return p_struct->variant_get_type(p_self);
}
GDExtensionBool cgo_callfn_GDExtensionInterface_variant_has_method(
    const GDExtensionInterface *p_struct, GDExtensionConstVariantPtr p_self,
    GDExtensionConstStringNamePtr p_method) {
  return p_struct->variant_has_method(p_self, p_method);
}
GDExtensionBool cgo_callfn_GDExtensionInterface_variant_has_member(
    const GDExtensionInterface *p_struct, GDExtensionVariantType p_type,
    GDExtensionConstStringNamePtr p_member) {
  return p_struct->variant_has_member(p_type, p_member);
}
GDExtensionBool cgo_callfn_GDExtensionInterface_variant_has_key(
    const GDExtensionInterface *p_struct, GDExtensionConstVariantPtr p_self,
    GDExtensionConstVariantPtr p_key, GDExtensionBool *r_valid) {
  return p_struct->variant_has_key(p_self, p_key, r_valid);
}
void cgo_callfn_GDExtensionInterface_variant_get_type_name(
    const GDExtensionInterface *p_struct, GDExtensionVariantType p_type,
    GDExtensionStringPtr r_name) {
  p_struct->variant_get_type_name(p_type, r_name);
}
GDExtensionBool cgo_callfn_GDExtensionInterface_variant_can_convert(
    const GDExtensionInterface *p_struct, GDExtensionVariantType p_from,
    GDExtensionVariantType p_to) {
  return p_struct->variant_can_convert(p_from, p_to);
}
GDExtensionBool cgo_callfn_GDExtensionInterface_variant_can_convert_strict(
    const GDExtensionInterface *p_struct, GDExtensionVariantType p_from,
    GDExtensionVariantType p_to) {
  return p_struct->variant_can_convert_strict(p_from, p_to);
}
GDExtensionVariantFromTypeConstructorFunc
cgo_callfn_GDExtensionInterface_get_variant_from_type_constructor(
    const GDExtensionInterface *p_struct, GDExtensionVariantType p_type) {
  return p_struct->get_variant_from_type_constructor(p_type);
}
GDExtensionTypeFromVariantConstructorFunc
cgo_callfn_GDExtensionInterface_get_variant_to_type_constructor(
    const GDExtensionInterface *p_struct, GDExtensionVariantType p_type) {
  return p_struct->get_variant_to_type_constructor(p_type);
}
GDExtensionPtrOperatorEvaluator
cgo_callfn_GDExtensionInterface_variant_get_ptr_operator_evaluator(
    const GDExtensionInterface *p_struct, GDExtensionVariantOperator p_operator,
    GDExtensionVariantType p_type_a, GDExtensionVariantType p_type_b) {
  return p_struct->variant_get_ptr_operator_evaluator(p_operator, p_type_a,
                                                      p_type_b);
}
GDExtensionPtrBuiltInMethod
cgo_callfn_GDExtensionInterface_variant_get_ptr_builtin_method(
    const GDExtensionInterface *p_struct, GDExtensionVariantType p_type,
    GDExtensionConstStringNamePtr p_method, GDExtensionInt p_hash) {
  return p_struct->variant_get_ptr_builtin_method(p_type, p_method, p_hash);
}
GDExtensionPtrConstructor
cgo_callfn_GDExtensionInterface_variant_get_ptr_constructor(
    const GDExtensionInterface *p_struct, GDExtensionVariantType p_type,
    int32_t p_constructor) {
  return p_struct->variant_get_ptr_constructor(p_type, p_constructor);
}
GDExtensionPtrDestructor
cgo_callfn_GDExtensionInterface_variant_get_ptr_destructor(
    const GDExtensionInterface *p_struct, GDExtensionVariantType p_type) {
  return p_struct->variant_get_ptr_destructor(p_type);
}
void cgo_callfn_GDExtensionInterface_variant_construct(
    const GDExtensionInterface *p_struct, GDExtensionVariantType p_type,
    GDExtensionVariantPtr p_base, const GDExtensionConstVariantPtr *p_args,
    int32_t p_argument_count, GDExtensionCallError *r_error) {
  p_struct->variant_construct(p_type, p_base, p_args, p_argument_count,
                              r_error);
}
GDExtensionPtrSetter cgo_callfn_GDExtensionInterface_variant_get_ptr_setter(
    const GDExtensionInterface *p_struct, GDExtensionVariantType p_type,
    GDExtensionConstStringNamePtr p_member) {
  return p_struct->variant_get_ptr_setter(p_type, p_member);
}
GDExtensionPtrGetter cgo_callfn_GDExtensionInterface_variant_get_ptr_getter(
    const GDExtensionInterface *p_struct, GDExtensionVariantType p_type,
    GDExtensionConstStringNamePtr p_member) {
  return p_struct->variant_get_ptr_getter(p_type, p_member);
}
GDExtensionPtrIndexedSetter
cgo_callfn_GDExtensionInterface_variant_get_ptr_indexed_setter(
    const GDExtensionInterface *p_struct, GDExtensionVariantType p_type) {
  return p_struct->variant_get_ptr_indexed_setter(p_type);
}
GDExtensionPtrIndexedGetter
cgo_callfn_GDExtensionInterface_variant_get_ptr_indexed_getter(
    const GDExtensionInterface *p_struct, GDExtensionVariantType p_type) {
  return p_struct->variant_get_ptr_indexed_getter(p_type);
}
GDExtensionPtrKeyedSetter
cgo_callfn_GDExtensionInterface_variant_get_ptr_keyed_setter(
    const GDExtensionInterface *p_struct, GDExtensionVariantType p_type) {
  return p_struct->variant_get_ptr_keyed_setter(p_type);
}
GDExtensionPtrKeyedGetter
cgo_callfn_GDExtensionInterface_variant_get_ptr_keyed_getter(
    const GDExtensionInterface *p_struct, GDExtensionVariantType p_type) {
  return p_struct->variant_get_ptr_keyed_getter(p_type);
}
GDExtensionPtrKeyedChecker
cgo_callfn_GDExtensionInterface_variant_get_ptr_keyed_checker(
    const GDExtensionInterface *p_struct, GDExtensionVariantType p_type) {
  return p_struct->variant_get_ptr_keyed_checker(p_type);
}
void cgo_callfn_GDExtensionInterface_variant_get_constant_value(
    const GDExtensionInterface *p_struct, GDExtensionVariantType p_type,
    GDExtensionConstStringNamePtr p_constant, GDExtensionVariantPtr r_ret) {
  p_struct->variant_get_constant_value(p_type, p_constant, r_ret);
}
GDExtensionPtrUtilityFunction
cgo_callfn_GDExtensionInterface_variant_get_ptr_utility_function(
    const GDExtensionInterface *p_struct,
    GDExtensionConstStringNamePtr p_function, GDExtensionInt p_hash) {
  return p_struct->variant_get_ptr_utility_function(p_function, p_hash);
}
void cgo_callfn_GDExtensionInterface_string_new_with_latin1_chars(
    const GDExtensionInterface *p_struct, GDExtensionStringPtr r_dest,
    const char *p_contents) {
  p_struct->string_new_with_latin1_chars(r_dest, p_contents);
}
void cgo_callfn_GDExtensionInterface_string_new_with_utf8_chars(
    const GDExtensionInterface *p_struct, GDExtensionStringPtr r_dest,
    const char *p_contents) {
  p_struct->string_new_with_utf8_chars(r_dest, p_contents);
}
void cgo_callfn_GDExtensionInterface_string_new_with_utf16_chars(
    const GDExtensionInterface *p_struct, GDExtensionStringPtr r_dest,
    const char16_t *p_contents) {
  p_struct->string_new_with_utf16_chars(r_dest, p_contents);
}
void cgo_callfn_GDExtensionInterface_string_new_with_utf32_chars(
    const GDExtensionInterface *p_struct, GDExtensionStringPtr r_dest,
    const char32_t *p_contents) {
  p_struct->string_new_with_utf32_chars(r_dest, p_contents);
}
void cgo_callfn_GDExtensionInterface_string_new_with_wide_chars(
    const GDExtensionInterface *p_struct, GDExtensionStringPtr r_dest,
    const wchar_t *p_contents) {
  p_struct->string_new_with_wide_chars(r_dest, p_contents);
}
void cgo_callfn_GDExtensionInterface_string_new_with_latin1_chars_and_len(
    const GDExtensionInterface *p_struct, GDExtensionStringPtr r_dest,
    const char *p_contents, GDExtensionInt p_size) {
  p_struct->string_new_with_latin1_chars_and_len(r_dest, p_contents, p_size);
}
void cgo_callfn_GDExtensionInterface_string_new_with_utf8_chars_and_len(
    const GDExtensionInterface *p_struct, GDExtensionStringPtr r_dest,
    const char *p_contents, GDExtensionInt p_size) {
  p_struct->string_new_with_utf8_chars_and_len(r_dest, p_contents, p_size);
}
void cgo_callfn_GDExtensionInterface_string_new_with_utf16_chars_and_len(
    const GDExtensionInterface *p_struct, GDExtensionStringPtr r_dest,
    const char16_t *p_contents, GDExtensionInt p_size) {
  p_struct->string_new_with_utf16_chars_and_len(r_dest, p_contents, p_size);
}
void cgo_callfn_GDExtensionInterface_string_new_with_utf32_chars_and_len(
    const GDExtensionInterface *p_struct, GDExtensionStringPtr r_dest,
    const char32_t *p_contents, GDExtensionInt p_size) {
  p_struct->string_new_with_utf32_chars_and_len(r_dest, p_contents, p_size);
}
void cgo_callfn_GDExtensionInterface_string_new_with_wide_chars_and_len(
    const GDExtensionInterface *p_struct, GDExtensionStringPtr r_dest,
    const wchar_t *p_contents, GDExtensionInt p_size) {
  p_struct->string_new_with_wide_chars_and_len(r_dest, p_contents, p_size);
}
GDExtensionInt cgo_callfn_GDExtensionInterface_string_to_latin1_chars(
    const GDExtensionInterface *p_struct, GDExtensionConstStringPtr p_self,
    char *r_text, GDExtensionInt p_max_write_length) {
  return p_struct->string_to_latin1_chars(p_self, r_text, p_max_write_length);
}
GDExtensionInt cgo_callfn_GDExtensionInterface_string_to_utf8_chars(
    const GDExtensionInterface *p_struct, GDExtensionConstStringPtr p_self,
    char *r_text, GDExtensionInt p_max_write_length) {
  return p_struct->string_to_utf8_chars(p_self, r_text, p_max_write_length);
}
GDExtensionInt cgo_callfn_GDExtensionInterface_string_to_utf16_chars(
    const GDExtensionInterface *p_struct, GDExtensionConstStringPtr p_self,
    char16_t *r_text, GDExtensionInt p_max_write_length) {
  return p_struct->string_to_utf16_chars(p_self, r_text, p_max_write_length);
}
GDExtensionInt cgo_callfn_GDExtensionInterface_string_to_utf32_chars(
    const GDExtensionInterface *p_struct, GDExtensionConstStringPtr p_self,
    char32_t *r_text, GDExtensionInt p_max_write_length) {
  return p_struct->string_to_utf32_chars(p_self, r_text, p_max_write_length);
}
GDExtensionInt cgo_callfn_GDExtensionInterface_string_to_wide_chars(
    const GDExtensionInterface *p_struct, GDExtensionConstStringPtr p_self,
    wchar_t *r_text, GDExtensionInt p_max_write_length) {
  return p_struct->string_to_wide_chars(p_self, r_text, p_max_write_length);
}
char32_t *cgo_callfn_GDExtensionInterface_string_operator_index(
    const GDExtensionInterface *p_struct, GDExtensionStringPtr p_self,
    GDExtensionInt p_index) {
  return p_struct->string_operator_index(p_self, p_index);
}
const char32_t *cgo_callfn_GDExtensionInterface_string_operator_index_const(
    const GDExtensionInterface *p_struct, GDExtensionConstStringPtr p_self,
    GDExtensionInt p_index) {
  return p_struct->string_operator_index_const(p_self, p_index);
}
void cgo_callfn_GDExtensionInterface_string_operator_plus_eq_string(
    const GDExtensionInterface *p_struct, GDExtensionStringPtr p_self,
    GDExtensionConstStringPtr p_b) {
  p_struct->string_operator_plus_eq_string(p_self, p_b);
}
void cgo_callfn_GDExtensionInterface_string_operator_plus_eq_char(
    const GDExtensionInterface *p_struct, GDExtensionStringPtr p_self,
    char32_t p_b) {
  p_struct->string_operator_plus_eq_char(p_self, p_b);
}
void cgo_callfn_GDExtensionInterface_string_operator_plus_eq_cstr(
    const GDExtensionInterface *p_struct, GDExtensionStringPtr p_self,
    const char *p_b) {
  p_struct->string_operator_plus_eq_cstr(p_self, p_b);
}
void cgo_callfn_GDExtensionInterface_string_operator_plus_eq_wcstr(
    const GDExtensionInterface *p_struct, GDExtensionStringPtr p_self,
    const wchar_t *p_b) {
  p_struct->string_operator_plus_eq_wcstr(p_self, p_b);
}
void cgo_callfn_GDExtensionInterface_string_operator_plus_eq_c32str(
    const GDExtensionInterface *p_struct, GDExtensionStringPtr p_self,
    const char32_t *p_b) {
  p_struct->string_operator_plus_eq_c32str(p_self, p_b);
}
GDExtensionInt cgo_callfn_GDExtensionInterface_xml_parser_open_buffer(
    const GDExtensionInterface *p_struct, GDExtensionObjectPtr p_instance,
    const uint8_t *p_buffer, size_t p_size) {
  return p_struct->xml_parser_open_buffer(p_instance, p_buffer, p_size);
}
void cgo_callfn_GDExtensionInterface_file_access_store_buffer(
    const GDExtensionInterface *p_struct, GDExtensionObjectPtr p_instance,
    const uint8_t *p_src, uint64_t p_length) {
  p_struct->file_access_store_buffer(p_instance, p_src, p_length);
}
uint64_t cgo_callfn_GDExtensionInterface_file_access_get_buffer(
    const GDExtensionInterface *p_struct, GDExtensionConstObjectPtr p_instance,
    uint8_t *p_dst, uint64_t p_length) {
  return p_struct->file_access_get_buffer(p_instance, p_dst, p_length);
}
int64_t
cgo_callfn_GDExtensionInterface_worker_thread_pool_add_native_group_task(
    const GDExtensionInterface *p_struct, GDExtensionObjectPtr p_instance,
    void (*p_func)(void *, uint32_t), void *p_userdata, int p_elements,
    int p_tasks, GDExtensionBool p_high_priority,
    GDExtensionConstStringPtr p_description) {
  return p_struct->worker_thread_pool_add_native_group_task(
      p_instance, p_func, p_userdata, p_elements, p_tasks, p_high_priority,
      p_description);
}
int64_t cgo_callfn_GDExtensionInterface_worker_thread_pool_add_native_task(
    const GDExtensionInterface *p_struct, GDExtensionObjectPtr p_instance,
    void (*p_func)(void *), void *p_userdata, GDExtensionBool p_high_priority,
    GDExtensionConstStringPtr p_description) {
  return p_struct->worker_thread_pool_add_native_task(
      p_instance, p_func, p_userdata, p_high_priority, p_description);
}
uint8_t *cgo_callfn_GDExtensionInterface_packed_byte_array_operator_index(
    const GDExtensionInterface *p_struct, GDExtensionTypePtr p_self,
    GDExtensionInt p_index) {
  return p_struct->packed_byte_array_operator_index(p_self, p_index);
}
const uint8_t *
cgo_callfn_GDExtensionInterface_packed_byte_array_operator_index_const(
    const GDExtensionInterface *p_struct, GDExtensionConstTypePtr p_self,
    GDExtensionInt p_index) {
  return p_struct->packed_byte_array_operator_index_const(p_self, p_index);
}
GDExtensionTypePtr
cgo_callfn_GDExtensionInterface_packed_color_array_operator_index(
    const GDExtensionInterface *p_struct, GDExtensionTypePtr p_self,
    GDExtensionInt p_index) {
  return p_struct->packed_color_array_operator_index(p_self, p_index);
}
GDExtensionTypePtr
cgo_callfn_GDExtensionInterface_packed_color_array_operator_index_const(
    const GDExtensionInterface *p_struct, GDExtensionConstTypePtr p_self,
    GDExtensionInt p_index) {
  return p_struct->packed_color_array_operator_index_const(p_self, p_index);
}
float *cgo_callfn_GDExtensionInterface_packed_float32_array_operator_index(
    const GDExtensionInterface *p_struct, GDExtensionTypePtr p_self,
    GDExtensionInt p_index) {
  return p_struct->packed_float32_array_operator_index(p_self, p_index);
}
const float *
cgo_callfn_GDExtensionInterface_packed_float32_array_operator_index_const(
    const GDExtensionInterface *p_struct, GDExtensionConstTypePtr p_self,
    GDExtensionInt p_index) {
  return p_struct->packed_float32_array_operator_index_const(p_self, p_index);
}
double *cgo_callfn_GDExtensionInterface_packed_float64_array_operator_index(
    const GDExtensionInterface *p_struct, GDExtensionTypePtr p_self,
    GDExtensionInt p_index) {
  return p_struct->packed_float64_array_operator_index(p_self, p_index);
}
const double *
cgo_callfn_GDExtensionInterface_packed_float64_array_operator_index_const(
    const GDExtensionInterface *p_struct, GDExtensionConstTypePtr p_self,
    GDExtensionInt p_index) {
  return p_struct->packed_float64_array_operator_index_const(p_self, p_index);
}
int32_t *cgo_callfn_GDExtensionInterface_packed_int32_array_operator_index(
    const GDExtensionInterface *p_struct, GDExtensionTypePtr p_self,
    GDExtensionInt p_index) {
  return p_struct->packed_int32_array_operator_index(p_self, p_index);
}
const int32_t *
cgo_callfn_GDExtensionInterface_packed_int32_array_operator_index_const(
    const GDExtensionInterface *p_struct, GDExtensionConstTypePtr p_self,
    GDExtensionInt p_index) {
  return p_struct->packed_int32_array_operator_index_const(p_self, p_index);
}
int64_t *cgo_callfn_GDExtensionInterface_packed_int64_array_operator_index(
    const GDExtensionInterface *p_struct, GDExtensionTypePtr p_self,
    GDExtensionInt p_index) {
  return p_struct->packed_int64_array_operator_index(p_self, p_index);
}
const int64_t *
cgo_callfn_GDExtensionInterface_packed_int64_array_operator_index_const(
    const GDExtensionInterface *p_struct, GDExtensionConstTypePtr p_self,
    GDExtensionInt p_index) {
  return p_struct->packed_int64_array_operator_index_const(p_self, p_index);
}
GDExtensionStringPtr
cgo_callfn_GDExtensionInterface_packed_string_array_operator_index(
    const GDExtensionInterface *p_struct, GDExtensionTypePtr p_self,
    GDExtensionInt p_index) {
  return p_struct->packed_string_array_operator_index(p_self, p_index);
}
GDExtensionStringPtr
cgo_callfn_GDExtensionInterface_packed_string_array_operator_index_const(
    const GDExtensionInterface *p_struct, GDExtensionConstTypePtr p_self,
    GDExtensionInt p_index) {
  return p_struct->packed_string_array_operator_index_const(p_self, p_index);
}
GDExtensionTypePtr
cgo_callfn_GDExtensionInterface_packed_vector2_array_operator_index(
    const GDExtensionInterface *p_struct, GDExtensionTypePtr p_self,
    GDExtensionInt p_index) {
  return p_struct->packed_vector2_array_operator_index(p_self, p_index);
}
GDExtensionTypePtr
cgo_callfn_GDExtensionInterface_packed_vector2_array_operator_index_const(
    const GDExtensionInterface *p_struct, GDExtensionConstTypePtr p_self,
    GDExtensionInt p_index) {
  return p_struct->packed_vector2_array_operator_index_const(p_self, p_index);
}
GDExtensionTypePtr
cgo_callfn_GDExtensionInterface_packed_vector3_array_operator_index(
    const GDExtensionInterface *p_struct, GDExtensionTypePtr p_self,
    GDExtensionInt p_index) {
  return p_struct->packed_vector3_array_operator_index(p_self, p_index);
}
GDExtensionTypePtr
cgo_callfn_GDExtensionInterface_packed_vector3_array_operator_index_const(
    const GDExtensionInterface *p_struct, GDExtensionConstTypePtr p_self,
    GDExtensionInt p_index) {
  return p_struct->packed_vector3_array_operator_index_const(p_self, p_index);
}
GDExtensionVariantPtr cgo_callfn_GDExtensionInterface_array_operator_index(
    const GDExtensionInterface *p_struct, GDExtensionTypePtr p_self,
    GDExtensionInt p_index) {
  return p_struct->array_operator_index(p_self, p_index);
}
GDExtensionVariantPtr
cgo_callfn_GDExtensionInterface_array_operator_index_const(
    const GDExtensionInterface *p_struct, GDExtensionConstTypePtr p_self,
    GDExtensionInt p_index) {
  return p_struct->array_operator_index_const(p_self, p_index);
}
GDExtensionVariantPtr cgo_callfn_GDExtensionInterface_dictionary_operator_index(
    const GDExtensionInterface *p_struct, GDExtensionTypePtr p_self,
    GDExtensionConstVariantPtr p_key) {
  return p_struct->dictionary_operator_index(p_self, p_key);
}
GDExtensionVariantPtr
cgo_callfn_GDExtensionInterface_dictionary_operator_index_const(
    const GDExtensionInterface *p_struct, GDExtensionConstTypePtr p_self,
    GDExtensionConstVariantPtr p_key) {
  return p_struct->dictionary_operator_index_const(p_self, p_key);
}
void cgo_callfn_GDExtensionInterface_object_method_bind_call(
    const GDExtensionInterface *p_struct,
    GDExtensionMethodBindPtr p_method_bind, GDExtensionObjectPtr p_instance,
    const GDExtensionConstVariantPtr *p_args, GDExtensionInt p_arg_count,
    GDExtensionVariantPtr r_ret, GDExtensionCallError *r_error) {
  p_struct->object_method_bind_call(p_method_bind, p_instance, p_args,
                                    p_arg_count, r_ret, r_error);
}
void cgo_callfn_GDExtensionInterface_object_method_bind_ptrcall(
    const GDExtensionInterface *p_struct,
    GDExtensionMethodBindPtr p_method_bind, GDExtensionObjectPtr p_instance,
    const GDExtensionConstTypePtr *p_args, GDExtensionTypePtr r_ret) {
  p_struct->object_method_bind_ptrcall(p_method_bind, p_instance, p_args,
                                       r_ret);
}
void cgo_callfn_GDExtensionInterface_object_destroy(
    const GDExtensionInterface *p_struct, GDExtensionObjectPtr p_o) {
  p_struct->object_destroy(p_o);
}
GDExtensionObjectPtr cgo_callfn_GDExtensionInterface_global_get_singleton(
    const GDExtensionInterface *p_struct,
    GDExtensionConstStringNamePtr p_name) {
  return p_struct->global_get_singleton(p_name);
}
void *cgo_callfn_GDExtensionInterface_object_get_instance_binding(
    const GDExtensionInterface *p_struct, GDExtensionObjectPtr p_o,
    void *p_token, const GDExtensionInstanceBindingCallbacks *p_callbacks) {
  return p_struct->object_get_instance_binding(p_o, p_token, p_callbacks);
}
void cgo_callfn_GDExtensionInterface_object_set_instance_binding(
    const GDExtensionInterface *p_struct, GDExtensionObjectPtr p_o,
    void *p_token, void *p_binding,
    const GDExtensionInstanceBindingCallbacks *p_callbacks) {
  p_struct->object_set_instance_binding(p_o, p_token, p_binding, p_callbacks);
}
void cgo_callfn_GDExtensionInterface_object_set_instance(
    const GDExtensionInterface *p_struct, GDExtensionObjectPtr p_o,
    GDExtensionConstStringNamePtr p_classname,
    GDExtensionClassInstancePtr p_instance) {
  p_struct->object_set_instance(p_o, p_classname, p_instance);
}
GDExtensionObjectPtr cgo_callfn_GDExtensionInterface_object_cast_to(
    const GDExtensionInterface *p_struct, GDExtensionConstObjectPtr p_object,
    void *p_class_tag) {
  return p_struct->object_cast_to(p_object, p_class_tag);
}
GDExtensionObjectPtr
cgo_callfn_GDExtensionInterface_object_get_instance_from_id(
    const GDExtensionInterface *p_struct, GDObjectInstanceID p_instance_id) {
  return p_struct->object_get_instance_from_id(p_instance_id);
}
GDObjectInstanceID cgo_callfn_GDExtensionInterface_object_get_instance_id(
    const GDExtensionInterface *p_struct, GDExtensionConstObjectPtr p_object) {
  return p_struct->object_get_instance_id(p_object);
}
GDExtensionObjectPtr cgo_callfn_GDExtensionInterface_ref_get_object(
    const GDExtensionInterface *p_struct, GDExtensionConstRefPtr p_ref) {
  return p_struct->ref_get_object(p_ref);
}
void cgo_callfn_GDExtensionInterface_ref_set_object(
    const GDExtensionInterface *p_struct, GDExtensionRefPtr p_ref,
    GDExtensionObjectPtr p_object) {
  p_struct->ref_set_object(p_ref, p_object);
}
GDExtensionScriptInstancePtr
cgo_callfn_GDExtensionInterface_script_instance_create(
    const GDExtensionInterface *p_struct,
    const GDExtensionScriptInstanceInfo *p_info,
    GDExtensionScriptInstanceDataPtr p_instance_data) {
  return p_struct->script_instance_create(p_info, p_instance_data);
}
GDExtensionObjectPtr cgo_callfn_GDExtensionInterface_classdb_construct_object(
    const GDExtensionInterface *p_struct,
    GDExtensionConstStringNamePtr p_classname) {
  return p_struct->classdb_construct_object(p_classname);
}
GDExtensionMethodBindPtr
cgo_callfn_GDExtensionInterface_classdb_get_method_bind(
    const GDExtensionInterface *p_struct,
    GDExtensionConstStringNamePtr p_classname,
    GDExtensionConstStringNamePtr p_methodname, GDExtensionInt p_hash) {
  return p_struct->classdb_get_method_bind(p_classname, p_methodname, p_hash);
}
void *cgo_callfn_GDExtensionInterface_classdb_get_class_tag(
    const GDExtensionInterface *p_struct,
    GDExtensionConstStringNamePtr p_classname) {
  return p_struct->classdb_get_class_tag(p_classname);
}
void cgo_callfn_GDExtensionInterface_classdb_register_extension_class(
    const GDExtensionInterface *p_struct, GDExtensionClassLibraryPtr p_library,
    GDExtensionConstStringNamePtr p_class_name,
    GDExtensionConstStringNamePtr p_parent_class_name,
    const GDExtensionClassCreationInfo *p_extension_funcs) {
  p_struct->classdb_register_extension_class(
      p_library, p_class_name, p_parent_class_name, p_extension_funcs);
}
void cgo_callfn_GDExtensionInterface_classdb_register_extension_class_method(
    const GDExtensionInterface *p_struct, GDExtensionClassLibraryPtr p_library,
    GDExtensionConstStringNamePtr p_class_name,
    const GDExtensionClassMethodInfo *p_method_info) {
  p_struct->classdb_register_extension_class_method(p_library, p_class_name,
                                                    p_method_info);
}
void cgo_callfn_GDExtensionInterface_classdb_register_extension_class_integer_constant(
    const GDExtensionInterface *p_struct, GDExtensionClassLibraryPtr p_library,
    GDExtensionConstStringNamePtr p_class_name,
    GDExtensionConstStringNamePtr p_enum_name,
    GDExtensionConstStringNamePtr p_constant_name,
    GDExtensionInt p_constant_value, GDExtensionBool p_is_bitfield) {
  p_struct->classdb_register_extension_class_integer_constant(
      p_library, p_class_name, p_enum_name, p_constant_name, p_constant_value,
      p_is_bitfield);
}
void cgo_callfn_GDExtensionInterface_classdb_register_extension_class_property(
    const GDExtensionInterface *p_struct, GDExtensionClassLibraryPtr p_library,
    GDExtensionConstStringNamePtr p_class_name,
    const GDExtensionPropertyInfo *p_info,
    GDExtensionConstStringNamePtr p_setter,
    GDExtensionConstStringNamePtr p_getter) {
  p_struct->classdb_register_extension_class_property(
      p_library, p_class_name, p_info, p_setter, p_getter);
}
void cgo_callfn_GDExtensionInterface_classdb_register_extension_class_property_group(
    const GDExtensionInterface *p_struct, GDExtensionClassLibraryPtr p_library,
    GDExtensionConstStringNamePtr p_class_name,
    GDExtensionConstStringPtr p_group_name,
    GDExtensionConstStringPtr p_prefix) {
  p_struct->classdb_register_extension_class_property_group(
      p_library, p_class_name, p_group_name, p_prefix);
}
void cgo_callfn_GDExtensionInterface_classdb_register_extension_class_property_subgroup(
    const GDExtensionInterface *p_struct, GDExtensionClassLibraryPtr p_library,
    GDExtensionConstStringNamePtr p_class_name,
    GDExtensionConstStringPtr p_subgroup_name,
    GDExtensionConstStringPtr p_prefix) {
  p_struct->classdb_register_extension_class_property_subgroup(
      p_library, p_class_name, p_subgroup_name, p_prefix);
}
void cgo_callfn_GDExtensionInterface_classdb_register_extension_class_signal(
    const GDExtensionInterface *p_struct, GDExtensionClassLibraryPtr p_library,
    GDExtensionConstStringNamePtr p_class_name,
    GDExtensionConstStringNamePtr p_signal_name,
    const GDExtensionPropertyInfo *p_argument_info,
    GDExtensionInt p_argument_count) {
  p_struct->classdb_register_extension_class_signal(
      p_library, p_class_name, p_signal_name, p_argument_info,
      p_argument_count);
}
void cgo_callfn_GDExtensionInterface_classdb_unregister_extension_class(
    const GDExtensionInterface *p_struct, GDExtensionClassLibraryPtr p_library,
    GDExtensionConstStringNamePtr p_class_name) {
  p_struct->classdb_unregister_extension_class(p_library, p_class_name);
}
void cgo_callfn_GDExtensionInterface_get_library_path(
    const GDExtensionInterface *p_struct, GDExtensionClassLibraryPtr p_library,
    GDExtensionStringPtr r_path) {
  p_struct->get_library_path(p_library, r_path);
}
/* struct (8) GDExtensionInitialization */
void cgo_callfn_GDExtensionInitialization_initialize(
    const GDExtensionInitialization *p_struct, void *userdata,
    GDExtensionInitializationLevel p_level) {
  p_struct->initialize(userdata, p_level);
}
void cgo_callfn_GDExtensionInitialization_deinitialize(
    const GDExtensionInitialization *p_struct, void *userdata,
    GDExtensionInitializationLevel p_level) {
  p_struct->deinitialize(userdata, p_level);
}
