name: Build Linux

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
        stable: true

    - name: Install Godot
      run: sudo apt-get install -y godot3-server

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Go get goimports
      run: go get golang.org/x/tools/cmd/goimports

    - name: Go Generate
      run: go generate

    - name: Build
      run: go run mage.go -v buildtest

    - name: Test
      run: go run mage.go -v test
